
window.LIPSYNC_SONG_GENRES = [
  "pop",
  "dance",
  "EDM",
  "house",
  "disco",
  "R&B",
  "soul",
  "funk",
  "hip-hop",
  "rock",
  "ballad",
  "camp",
  "theatre",
  "country",
  "Latin",
  "K-pop",
  "alternative",
  "hyperpop",
  "new wave",
  "diva"
];

window.LIPSYNC_SONGS = [
  { id:"song_001", song:"yes, and?", artist:"Ariana Grande", genres:["pop"] },
  { id:"song_002", song:"The Way That You Love Me", artist:"Paula Abdul", genres:["pop", "dance"] },
  { id:"song_003", song:"Buttons", artist:"The Pussycat Dolls feat. Snoop Dogg", genres:["pop", "dance"] },
  { id:"song_004", song:"Boogie Wonderland", artist:"Earth, Wind & Fire and The Emotions", genres:["disco", "dance", "soul", "funk"] },
  { id:"song_005", song:"get him back!", artist:"Olivia Rodrigo", genres:["rock"] },
  { id:"song_006", song:"Hands to Myself", artist:"Selena Gomez", genres:["pop"] },
  { id:"song_007", song:"WET DREAM", artist:"Adam Lambert", genres:["pop"] },
  { id:"song_008", song:"Kiss Me Deadly", artist:"Lita Ford", genres:["rock"] },
  { id:"song_009", song:"YA YA", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_010", song:"Unholy", artist:"Sam Smith and Kim Petras", genres:["dance"] },
  { id:"song_011", song:"Illusion", artist:"Dua Lipa", genres:["pop", "dance"] },
  { id:"song_012", song:"1 Thing", artist:"Amerie", genres:["pop"] },
  { id:"song_013", song:"Love Child", artist:"Diana Ross & The Supremes", genres:["soul", "funk"] },
  { id:"song_014", song:"Woman's World", artist:"Katy Perry", genres:["diva", "pop"] },
  { id:"song_015", song:"Alter Ego", artist:"Doechii & JT", genres:["hip-hop"] },
  { id:"song_016", song:"Say Liza (Liza with a “Z”)", artist:"Liza Minnelli", genres:["theatre", "camp"] },
  { id:"song_017", song:"Training Season", artist:"Dua Lipa", genres:["pop", "dance"] },
  { id:"song_018", song:"Step by Step (Junior Vasquez Tribal X Beats)", artist:"Whitney Houston", genres:["house", "dance", "R&B"] },
  { id:"song_019", song:"Blow Me (One Last Kiss)", artist:"P!nk", genres:["pop"] },
  { id:"song_020", song:"You Make Me Feel (Mighty Real)", artist:"Sylvester", genres:["disco", "dance"] },
  { id:"song_021", song:"We Found Love", artist:"Rihanna", genres:["pop"] },
  { id:"song_022", song:"360", artist:"Charli XCX", genres:["hyperpop", "dance"] },
  { id:"song_023", song:"APT.", artist:"ROSÉ and Bruno Mars", genres:["K-pop", "pop"] },
  { id:"song_024", song:"Abracadabra", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_025", song:"Maybe You're the Problem", artist:"Ava Max", genres:["pop", "dance"] },
  { id:"song_026", song:"Dark Lady", artist:"Cher", genres:["diva", "pop"] },
  { id:"song_027", song:"Emergency", artist:"Icona Pop", genres:["dance"] },
  { id:"song_028", song:"Control", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_029", song:"Flowers", artist:"Miley Cyrus", genres:["pop"] },
  { id:"song_030", song:"I Wanna Dance With Somebody", artist:"Whitney Houston", genres:["R&B", "dance"] },
  { id:"song_031", song:"Bloody Mary", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_032", song:"Dim All the Lights", artist:"Donna Summer", genres:["disco", "dance"] },
  { id:"song_033", song:"Body", artist:"Megan Thee Stallion", genres:["hip-hop", "dance"] },
  { id:"song_034", song:"Miss Me More", artist:"Kelsea Ballerini", genres:["country"] },
  { id:"song_035", song:"Better Be Good to Me", artist:"Tina Turner", genres:["soul", "funk"] },
  { id:"song_036", song:"Break My Soul", artist:"Beyoncé", genres:["house", "dance", "R&B"] },
  { id:"song_037", song:"Shower", artist:"Becky G", genres:["pop"] },
  { id:"song_038", song:"Made You Look", artist:"Meghan Trainor", genres:["pop"] },
  { id:"song_039", song:"Damaged", artist:"Danity Kane", genres:["pop"] },
  { id:"song_040", song:"What About", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_041", song:"Million Dollar Baby", artist:"Ava Max", genres:["pop", "dance"] },
  { id:"song_042", song:"Alone 2.0", artist:"Kim Petras & Nicki Minaj", genres:["dance", "hip-hop"] },
  { id:"song_043", song:"Milkshake", artist:"Kelis", genres:["R&B", "camp"] },
  { id:"song_044", song:"The Shoop Shoop Song", artist:"Cher", genres:["pop"] },
  { id:"song_045", song:"This Time I Know It's For Real", artist:"Donna Summer", genres:["disco", "dance"] },
  { id:"song_046", song:"We Got the Beat", artist:"The Go-Go's", genres:["rock", "new wave", "pop", "dance"] },
  { id:"song_047", song:"Gonna Make You Sweat (Everybody Dance Now)", artist:"C+C Music Factory", genres:["house", "dance"] },
  { id:"song_048", song:"7 Rings", artist:"Ariana Grande", genres:["pop"] },
  { id:"song_049", song:"Ain't No Mountain High Enough", artist:"Diana Ross", genres:["soul", "funk"] },
  { id:"song_050", song:"You Better Run", artist:"Pat Benatar", genres:["rock"] },
  { id:"song_051", song:"Q.U.E.E.N.", artist:"Janelle Monáe", genres:["R&B"] },
  { id:"song_052", song:"In Your Room", artist:"The Bangles", genres:["rock", "new wave", "pop"] },
  { id:"song_053", song:"Sweetest Pie", artist:"Megan Thee Stallion & Dua Lipa", genres:["hip-hop", "pop", "dance"] },
  { id:"song_054", song:"That's What I Want", artist:"Lil Nas X", genres:["hip-hop"] },
  { id:"song_055", song:"Single Ladies", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_056", song:"Boss Bitch", artist:"Doja Cat", genres:["diva", "pop"] },
  { id:"song_057", song:"Running Up That Hill", artist:"Kate Bush", genres:["rock", "alternative"] },
  { id:"song_058", song:"For the Girls", artist:"Hayley Kiyoko", genres:["diva", "pop"] },
  { id:"song_059", song:"When Love Takes Over", artist:"David Guetta feat. Kelly Rowland", genres:["EDM", "dance"] },
  { id:"song_060", song:"Boys Don't Cry", artist:"Anitta", genres:["pop"] },
  { id:"song_061", song:"Do You Wanna Touch", artist:"Joan Jett", genres:["rock"] },
  { id:"song_062", song:"It's All Coming Back to Me Now", artist:"Celine Dion", genres:["ballad", "diva"] },
  { id:"song_063", song:"Tell It to My Heart", artist:"Taylor Dayne", genres:["pop"] },
  { id:"song_064", song:"I'm in Love with a Monster", artist:"Fifth Harmony", genres:["pop"] },
  { id:"song_065", song:"Don't Go Yet", artist:"Camila Cabello", genres:["Latin", "dance", "pop"] },
  { id:"song_066", song:"The Right Stuff", artist:"Vanessa Williams", genres:["pop"] },
  { id:"song_067", song:"Finally", artist:"CeCe Peniston", genres:["disco", "dance"] },
  { id:"song_068", song:"Water Me", artist:"Lizzo", genres:["pop"] },
  { id:"song_069", song:"Fallin'", artist:"Alicia Keys", genres:["ballad", "diva", "R&B"] },
  { id:"song_070", song:"I Love It", artist:"Kylie Minogue", genres:["pop", "dance"] },
  { id:"song_071", song:"Play", artist:"Jennifer Lopez", genres:["pop", "dance"] },
  { id:"song_072", song:"My Head & My Heart", artist:"Ava Max", genres:["pop", "dance"] },
  { id:"song_073", song:"Suga Mama", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_074", song:"Un-Break My Heart (Hex Hector Remix)", artist:"Toni Braxton", genres:["ballad", "diva", "R&B"] },
  { id:"song_075", song:"Something's Got a Hold on Me", artist:"Etta James", genres:["soul", "funk"] },
  { id:"song_076", song:"Heartbreak Hotel (Hex Hector Remix)", artist:"Whitney Houston", genres:["R&B"] },
  { id:"song_077", song:"good 4 u", artist:"Olivia Rodrigo", genres:["rock"] },
  { id:"song_078", song:"Telephone", artist:"Lady Gaga ft. Beyoncé", genres:["R&B", "pop", "dance"] },
  { id:"song_079", song:"One Way or Another", artist:"Blondie", genres:["rock", "new wave", "pop"] },
  { id:"song_080", song:"Respect", artist:"Aretha Franklin", genres:["R&B"] },
  { id:"song_081", song:"Never Too Much", artist:"Luther Vandross", genres:["soul", "funk"] },
  { id:"song_082", song:"Radio", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_083", song:"Don't Let Go (Love)", artist:"En Vogue", genres:["R&B"] },
  { id:"song_084", song:"Love Don't Cost a Thing", artist:"Jennifer Lopez", genres:["pop", "dance"] },
  { id:"song_085", song:"Swept Away", artist:"Diana Ross", genres:["soul", "funk"] },
  { id:"song_086", song:"100% Pure Love", artist:"Crystal Waters", genres:["house", "dance"] },
  { id:"song_087", song:"Fancy", artist:"Iggy Azalea feat. Charli XCX", genres:["country", "hyperpop", "hip-hop", "dance"] },
  { id:"song_088", song:"Hit 'Em Up Style (Oops!)", artist:"Blu Cantrell", genres:["pop"] },
  { id:"song_089", song:"Whole Lotta Woman", artist:"Kelly Clarkson", genres:["diva", "pop"] },
  { id:"song_090", song:"BO$$", artist:"Fifth Harmony", genres:["pop"] },
  { id:"song_091", song:"Fascinated", artist:"Company B", genres:["dance"] },
  { id:"song_092", song:"Shackles (Praise You)", artist:"Mary Mary", genres:["pop"] },
  { id:"song_093", song:"My Humps", artist:"Black Eyed Peas", genres:["hip-hop", "camp"] },
  { id:"song_094", song:"No Tears Left to Cry", artist:"Ariana Grande", genres:["pop"] },
  { id:"song_095", song:"Strong Enough", artist:"Cher", genres:["diva", "pop"] },
  { id:"song_096", song:"I Learned from the Best (HQ2 Radio Mix)", artist:"Whitney Houston", genres:["ballad", "diva", "R&B"] },
  { id:"song_097", song:"Break My Heart", artist:"Dua Lipa", genres:["pop", "dance"] },
  { id:"song_098", song:"If U Seek Amy", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_099", song:"Call Me Maybe", artist:"Carly Rae Jepsen", genres:["pop"] },
  { id:"song_100", song:"When I Grow Up", artist:"The Pussycat Dolls", genres:["pop", "dance"] },
  { id:"song_101", song:"The Pleasure Principle", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_102", song:"Rumors", artist:"Lindsay Lohan", genres:["pop"] },
  { id:"song_103", song:"Ex's & Oh's", artist:"Elle King", genres:["rock"] },
  { id:"song_104", song:"Lady Marmalade", artist:"Christina Aguilera, Lil' Kim, Mýa & Pink", genres:["R&B", "diva", "pop"] },
  { id:"song_105", song:"Problem", artist:"Ariana Grande feat. Iggy Azalea", genres:["hip-hop", "pop"] },
  { id:"song_106", song:"S&M", artist:"Rihanna", genres:["camp", "pop"] },
  { id:"song_107", song:"Heart to Break", artist:"Kim Petras", genres:["dance"] },
  { id:"song_108", song:"Let It Go", artist:"Caissie Levy", genres:["theatre", "camp"] },
  { id:"song_109", song:"Burning Up", artist:"Madonna", genres:["rock", "pop", "dance"] },
  { id:"song_110", song:"This is My Night", artist:"Chaka Khan", genres:["soul", "funk"] },
  { id:"song_111", song:"Firework", artist:"Katy Perry", genres:["dance", "pop"] },
  { id:"song_112", song:"Kill the Lights", artist:"Alex Newell", genres:["pop"] },
  { id:"song_113", song:"1999", artist:"Prince", genres:["soul", "funk"] },
  { id:"song_114", song:"On the Floor", artist:"Jennifer Lopez feat. Pitbull", genres:["Latin", "dance", "pop"] },
  { id:"song_115", song:"Starships", artist:"Nicki Minaj", genres:["hip-hop"] },
  { id:"song_116", song:"Call Your Girlfriend", artist:"Robyn", genres:["diva", "pop"] },
  { id:"song_117", song:"Get Up", artist:"Ciara", genres:["R&B"] },
  { id:"song_118", song:"Survivor", artist:"Destiny's Child", genres:["R&B", "diva"] },
  { id:"song_119", song:"Take on Me", artist:"a-ha", genres:["rock", "new wave", "pop"] },
  { id:"song_120", song:"Best of Both Worlds", artist:"Miley Cyrus", genres:["pop"] },
  { id:"song_121", song:"Work Bitch", artist:"Britney Spears", genres:["dance", "diva", "pop"] },
  { id:"song_122", song:"Waiting for Tonight (Hex Hector Remix)", artist:"Jennifer Lopez", genres:["dance", "pop"] },
  { id:"song_123", song:"Living in America", artist:"James Brown", genres:["soul", "funk"] },
  { id:"song_124", song:"I'm Your Baby Tonight", artist:"Whitney Houston", genres:["R&B", "dance"] },
  { id:"song_125", song:"Last Dance", artist:"Donna Summer", genres:["disco", "dance"] },
  { id:"song_126", song:"Strut", artist:"Sheena Easton", genres:["pop"] },
  { id:"song_127", song:"Sorry Not Sorry", artist:"Demi Lovato", genres:["pop"] },
  { id:"song_128", song:"Hood Boy", artist:"Fantasia", genres:["R&B"] },
  { id:"song_129", song:"No More Drama", artist:"Mary J. Blige", genres:["ballad", "diva", "R&B"] },
  { id:"song_130", song:"No Scrubs", artist:"TLC", genres:["R&B"] },
  { id:"song_131", song:"Pride: A Deeper Love", artist:"Aretha Franklin", genres:["house", "dance", "R&B"] },
  { id:"song_132", song:"Bootylicious", artist:"Destiny's Child", genres:["R&B", "camp"] },
  { id:"song_133", song:"SOS", artist:"Rihanna", genres:["pop"] },
  { id:"song_134", song:"The Edge of Glory", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_135", song:"Ain't No Other Man", artist:"Christina Aguilera", genres:["pop"] },
  { id:"song_136", song:"Best of My Love", artist:"The Emotions", genres:["soul", "funk"] },
  { id:"song_137", song:"Celebrity Skin", artist:"Hole", genres:["rock"] },
  { id:"song_138", song:"Pound the Alarm", artist:"Nicki Minaj", genres:["hip-hop"] },
  { id:"song_139", song:"Man! I Feel Like a Woman", artist:"Shania Twain", genres:["country", "diva"] },
  { id:"song_140", song:"I'm Coming Out", artist:"Diana Ross", genres:["soul", "funk"] },
  { id:"song_141", song:"Cut to the Feeling", artist:"Carly Rae Jepsen", genres:["pop"] },
  { id:"song_142", song:"Groove is in the Heart", artist:"Deee-Lite", genres:["dance"] },
  { id:"song_143", song:"New Attitude", artist:"Patti LaBelle", genres:["soul", "funk"] },
  { id:"song_144", song:"Good As Hell", artist:"Lizzo", genres:["pop"] },
  { id:"song_145", song:"Nasty Girl", artist:"Vanity 6", genres:["diva", "camp"] },
  { id:"song_146", song:"Nasty", artist:"Janet Jackson", genres:["R&B", "camp", "dance"] },
  { id:"song_147", song:"If", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_148", song:"Bang Bang", artist:"Jessie J, Ariana Grande and Nicki Minaj", genres:["hip-hop", "pop"] },
  { id:"song_149", song:"Love Shack", artist:"The B-52's", genres:["camp", "new wave", "pop"] },
  { id:"song_150", song:"Holding Out for a Hero", artist:"Bonnie Tyler", genres:["diva", "pop"] },
  { id:"song_151", song:"I Wanna Go", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_152", song:"Woman Up", artist:"Meghan Trainor", genres:["diva", "pop"] },
  { id:"song_153", song:"Music", artist:"Madonna", genres:["dance", "pop"] },
  { id:"song_154", song:"Finally", artist:"Cece Peniston", genres:["disco", "dance"] },
  { id:"song_155", song:"Baby I'm Burnin", artist:"Dolly Parton", genres:["country"] },
  { id:"song_156", song:"Greedy", artist:"Ariana Grande", genres:["pop"] },
  { id:"song_157", song:"Cool for the Summer", artist:"Demi Lovato", genres:["pop"] },
  { id:"song_158", song:"Macho Man", artist:"The Village People", genres:["camp", "pop"] },
  { id:"song_159", song:"Applause", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_160", song:"I Will Survive", artist:"Gloria Gaynor", genres:["disco", "dance"] },
  { id:"song_161", song:"Mesmerized", artist:"Faith Evans", genres:["pop"] },
  { id:"song_162", song:"Call Me", artist:"Blondie", genres:["rock", "new wave", "pop"] },
  { id:"song_163", song:"Causing a Commotion", artist:"Madonna", genres:["pop", "dance"] },
  { id:"song_164", song:"I Love It", artist:"Icona Pop", genres:["dance"] },
  { id:"song_165", song:"And I Am Telling You I'm Not Going", artist:"Jennifer Holliday", genres:["ballad", "diva"] },
  { id:"song_166", song:"Geronimo", artist:"RuPaul feat. Lucian Piane", genres:["camp", "dance"] },
  { id:"song_167", song:"Twist of Fate", artist:"Olivia Newton-John", genres:["pop"] },
  { id:"song_168", song:"I Was Gonna Cancel", artist:"Kylie Minogue", genres:["pop", "dance"] },
  { id:"song_169", song:"Dreaming", artist:"Blondie", genres:["rock", "new wave", "pop"] },
  { id:"song_170", song:"Lovergirl", artist:"Teena Marie", genres:["R&B", "diva"] },
  { id:"song_171", song:"Break Free", artist:"Ariana Grande", genres:["pop"] },
  { id:"song_172", song:"No More Lies", artist:"Michel'le", genres:["R&B"] },
  { id:"song_173", song:"I Think We're Alone Now", artist:"Tiffany", genres:["pop"] },
  { id:"song_174", song:"Really Don't Care", artist:"Demi Lovato feat. Cher Lloyd", genres:["pop"] },
  { id:"song_175", song:"Show Me Love", artist:"Robin S.", genres:["house", "dance"] },
  { id:"song_176", song:"Roar", artist:"Katy Perry", genres:["pop"] },
  { id:"song_177", song:"Express Yourself", artist:"Madonna", genres:["pop", "dance"] },
  { id:"song_178", song:"Turn the Beat Around", artist:"Vicki Sue Robinson", genres:["dance"] },
  { id:"song_179", song:"Shake It Up", artist:"Selena Gomez", genres:["pop"] },
  { id:"song_180", song:"I'm Every Woman", artist:"Chaka Khan", genres:["soul", "funk", "diva"] },
  { id:"song_181", song:"Head to Toe", artist:"Lisa Lisa & Cult Jam", genres:["K-pop", "pop", "soul", "funk"] },
  { id:"song_182", song:"Whatta Man", artist:"Salt-n-Pepa feat. En Vogue", genres:["hip-hop", "R&B"] },
  { id:"song_183", song:"Point of No Return", artist:"Exposé", genres:["dance"] },
  { id:"song_184", song:"Stupid Girls", artist:"P!nk", genres:["diva", "pop"] },
  { id:"song_185", song:"Vibeology", artist:"Paula Abdul", genres:["dance", "pop"] },
  { id:"song_186", song:"Think", artist:"Aretha Franklin", genres:["R&B"] },
  { id:"song_187", song:"Stronger (What Doesn't Kill You)", artist:"Kelly Clarkson", genres:["diva", "pop"] },
  { id:"song_188", song:"Party in the U.S.A.", artist:"Miley Cyrus", genres:["dance", "pop"] },
  { id:"song_189", song:"Only Girl (in the World)", artist:"Rihanna", genres:["diva", "pop"] },
  { id:"song_190", song:"When I Grow Up", artist:"Pussycat Dolls", genres:["pop", "dance"] },
  { id:"song_191", song:"Oops!...I Did It Again", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_192", song:"Take Me Home", artist:"Cher", genres:["disco", "dance", "pop"] },
  { id:"song_193", song:"I'm So Excited", artist:"The Pointer Sisters", genres:["pop"] },
  { id:"song_194", song:"Whip My Hair", artist:"Willow Smith", genres:["hip-hop"] },
  { id:"song_195", song:"Ain't Nothin' Going on but the Rent", artist:"Gwen Guthrie", genres:["pop"] },
  { id:"song_196", song:"Cold Hearted", artist:"Paula Abdul", genres:["pop", "dance"] },
  { id:"song_197", song:"(It Takes) Two to Make It Right", artist:"Seduction", genres:["pop"] },
  { id:"song_198", song:"Malambo No. 1", artist:"Yma Sumac", genres:["theatre", "camp"] },
  { id:"song_199", song:"Toxic", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_200", song:"Bad Girls", artist:"Donna Summer", genres:["diva", "dance"] },
  { id:"song_201", song:"This Will Be (An Everlasting Love)", artist:"Natalie Cole", genres:["soul", "funk"] },
  { id:"song_202", song:"Trouble", artist:"Pink", genres:["rock", "pop"] },
  { id:"song_203", song:"Vogue", artist:"Madonna", genres:["house", "dance", "pop"] },
  { id:"song_204", song:"Born This Way", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_205", song:"Mi Vida Loca", artist:"Pam Tillis", genres:["country", "Latin", "dance"] },
  { id:"song_206", song:"It's Raining Men (The Sequel)", artist:"Martha Wash and RuPaul", genres:["dance"] },
  { id:"song_207", song:"I've Got to Use My Imagination", artist:"Gladys Knight", genres:["soul", "funk"] },
  { id:"song_208", song:"(You Make Me Feel Like) A Natural Woman", artist:"Aretha Franklin", genres:["R&B", "diva"] },
  { id:"song_209", song:"No One Else On Earth", artist:"Wynonna Judd", genres:["country"] },
  { id:"song_210", song:"The Right Stuff", artist:"Vanessa Williams", genres:["pop"] },
  { id:"song_211", song:"Bad Romance", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_212", song:"Don't Leave Me This Way", artist:"Thelma Houston", genres:["disco", "dance"] },
  { id:"song_213", song:"Meeting in the Ladies Room", artist:"Klymaxx", genres:["soul", "funk"] },
  { id:"song_214", song:"Lookin for a New Love", artist:"Jody Watley", genres:["pop"] },
  { id:"song_215", song:"Knock on Wood", artist:"Amii Stewart", genres:["disco", "dance"] },
  { id:"song_216", song:"MacArthur Park", artist:"Donna Summer", genres:["disco", "dance"] },
  { id:"song_217", song:"Hey Mickey (Spanish Version)", artist:"Toni Basil", genres:["camp", "pop"] },
  { id:"song_218", song:"Believe", artist:"Cher", genres:["pop"] },
  { id:"song_219", song:"Even Angels", artist:"Fantasia", genres:["ballad", "diva", "R&B"] },
  { id:"song_220", song:"Straight Up", artist:"Paula Abdul", genres:["pop", "dance"] },
  { id:"song_221", song:"I Think About You", artist:"Patti LaBelle", genres:["soul", "funk"] },
  { id:"song_222", song:"Covergirl (Put the Bass in Your Walk)", artist:"RuPaul", genres:["camp", "diva", "dance"] },
  { id:"song_223", song:"My Lovin' (You're Never Gonna Get It)", artist:"En Vogue", genres:["R&B"] },
  { id:"song_224", song:"I Hear You Knocking", artist:"Wynonna Judd", genres:["country"] },
  { id:"song_225", song:"Two of Hearts", artist:"Stacey Q", genres:["pop"] },
  { id:"song_226", song:"Carry On", artist:"Martha Wash", genres:["house", "dance"] },
  { id:"song_227", song:"Black Velvet", artist:"Alannah Myles", genres:["ballad", "diva"] },
  { id:"song_228", song:"He's the Greatest Dancer", artist:"Sister Sledge", genres:["disco", "dance"] },
  { id:"song_229", song:"Shake Your Love", artist:"Debbie Gibson", genres:["pop"] },
  { id:"song_230", song:"Something He Can Feel", artist:"Aretha Franklin", genres:["R&B"] },
  { id:"song_231", song:"Supermodel", artist:"RuPaul", genres:["camp", "dance"] },
  { id:"song_232", song:"We Break the Dawn", artist:"Michelle Williams", genres:["pop"] },
  { id:"song_233", song:"The Greatest Love of All", artist:"Whitney Houston", genres:["ballad", "diva", "R&B"] },
  { id:"song_234", song:"Would I Lie to You?", artist:"Eurythmics", genres:["new wave", "pop"] },
  { id:"song_235", song:"Stronger", artist:"Britney Spears", genres:["diva", "pop", "dance"] },
  { id:"song_236", song:"Shackles (Praise You)", artist:"Mary Mary", genres:["pop"] },
  { id:"song_237", song:"Think U the Shit (Fart)", artist:"Ice Spice", genres:["camp", "hip-hop"] },
  { id:"song_238", song:"Murder on the Dancefloor", artist:"Sophie Ellis-Bextor", genres:["disco", "dance", "hyperpop", "alternative"] },
  { id:"song_239", song:"Pocketbook", artist:"Jennifer Hudson", genres:["pop"] },
  { id:"song_240", song:"Love Sensation", artist:"Loleatta Holloway", genres:["disco", "dance"] },
  { id:"song_241", song:"HOT TO GO!", artist:"Chappell Roan", genres:["camp", "pop"] },
  { id:"song_242", song:"TEXAS HOLD 'EM", artist:"Beyoncé", genres:["country", "R&B"] },
  { id:"song_243", song:"Defying Gravity", artist:"Idina Menzel and Kristin Chenoweth", genres:["theatre", "camp"] },
  { id:"song_244", song:"See You Again", artist:"Miley Cyrus", genres:["pop"] },
  { id:"song_245", song:"Mama Used to Say", artist:"Junior", genres:["soul", "funk"] },
  { id:"song_246", song:"Who's Zoomin' Who - Acapella Mix", artist:"Aretha Franklin", genres:["R&B"] },
  { id:"song_247", song:"Guess", artist:"Charli XCX and Billie Eilish", genres:["hyperpop", "alternative", "dance"] },
  { id:"song_248", song:"Disease", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_249", song:"JOYRIDE.", artist:"Kesha", genres:["pop"] },
  { id:"song_250", song:"Party Lights", artist:"Natalie Cole", genres:["soul", "funk", "dance"] },
  { id:"song_251", song:"Show Me How You Burlesque", artist:"Christina Aguilera", genres:["pop"] },
  { id:"song_252", song:"Raise Your Glass", artist:"P!nk", genres:["pop"] },
  { id:"song_253", song:"Whenever, Wherever", artist:"Shakira", genres:["Latin", "dance"] },
  { id:"song_254", song:"It's Raining Men", artist:"The Weather Girls", genres:["camp", "disco", "dance"] },
  { id:"song_255", song:"Million Dollar Bill (Freemasons Radio Mix)", artist:"Whitney Houston", genres:["house", "dance", "R&B"] },
  { id:"song_256", song:"Jump in the Line", artist:"Harry Belafonte", genres:["camp", "dance"] },
  { id:"song_257", song:"Banana", artist:"Anitta feat. Becky G", genres:["Latin", "dance"] },
  { id:"song_258", song:"Black Cat", artist:"Janet Jackson", genres:["rock", "R&B", "dance"] },
  { id:"song_259", song:"Super Freaky Girl", artist:"Nicki Minaj", genres:["hip-hop", "diva", "camp"] },
  { id:"song_260", song:"Be My Lover", artist:"La Bouche", genres:["EDM", "dance"] },
  { id:"song_261", song:"Lovergirl", artist:"Teena Marie", genres:["R&B", "diva"] },
  { id:"song_262", song:"No One Gets the Prize", artist:"Diana Ross", genres:["disco", "dance", "soul", "funk"] },
  { id:"song_263", song:"Love Come Home (Subgroover's Music Video Edit)", artist:"Kristine W", genres:["house", "dance"] },
  { id:"song_264", song:"Rhythm Nation", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_265", song:"Freakum Dress", artist:"Beyoncé", genres:["R&B", "camp"] },
  { id:"song_266", song:"She Bop", artist:"Cyndi Lauper", genres:["pop"] },
  { id:"song_267", song:"Coconuts", artist:"Kim Petras", genres:["camp", "dance"] },
  { id:"song_268", song:"Bad Reputation", artist:"Joan Jett", genres:["rock"] },
  { id:"song_269", song:"Hallucinate", artist:"Dua Lipa", genres:["house", "dance", "pop"] },
  { id:"song_270", song:"I'm Not Perfect But I'm Perfect for You", artist:"Grace Jones", genres:["EDM", "dance"] },
  { id:"song_271", song:"About Damn Time", artist:"Lizzo", genres:["pop"] },
  { id:"song_272", song:"These Boots Were Made for Walkin'", artist:"Nancy Sinatra", genres:["rock"] },
  { id:"song_273", song:"Freak-A-Zoid", artist:"Midnight Star", genres:["soul", "funk", "camp"] },
  { id:"song_274", song:"Jumpin' Jumpin'", artist:"Destiny's Child", genres:["R&B", "dance"] },
  { id:"song_275", song:"Rain On Me", artist:"Lady Gaga & Ariana Grande", genres:["house", "dance", "pop"] },
  { id:"song_276", song:"Do You Wanna Funk", artist:"Sylvester & Patrick Cowley", genres:["disco", "dance"] },
  { id:"song_277", song:"Old MacDonald", artist:"Ella Fitzgerald", genres:["theatre", "camp"] },
  { id:"song_278", song:"Rumour Has It", artist:"Adele", genres:["pop"] },
  { id:"song_279", song:"Green Light", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_280", song:"Love Will Save The Day", artist:"Whitney Houston", genres:["R&B"] },
  { id:"song_281", song:"Better in Color", artist:"Lizzo", genres:["pop"] },
  { id:"song_282", song:"Why'd You Come in Here Looking Like That", artist:"Dolly Parton", genres:["country"] },
  { id:"song_283", song:"I Want Love", artist:"Jessie J", genres:["pop"] },
  { id:"song_284", song:"Super Freak", artist:"Rick James", genres:["soul", "funk", "camp"] },
  { id:"song_285", song:"Designing Women", artist:"Dixie Carter", genres:["theatre", "camp"] },
  { id:"song_286", song:"Kings & Queens", artist:"Ava Max", genres:["diva", "pop", "dance"] },
  { id:"song_287", song:"Supernova", artist:"Kylie Minogue", genres:["pop", "dance"] },
  { id:"song_288", song:"Push It", artist:"Salt-N-Pepa", genres:["hip-hop"] },
  { id:"song_289", song:"Let's Hear It for the Boy", artist:"Deniece Williams", genres:["pop"] },
  { id:"song_290", song:"Sisters Are Doin' It for Themselves", artist:"Eurythmics and Aretha Franklin", genres:["new wave", "pop", "R&B"] },
  { id:"song_291", song:"Judas", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_292", song:"So What", artist:"Pink", genres:["pop"] },
  { id:"song_293", song:"Swish Swish", artist:"Katy Perry feat. Nicki Minaj", genres:["hip-hop", "pop"] },
  { id:"song_294", song:"Uptown Funk", artist:"Mark Ronson feat. Bruno Mars", genres:["pop"] },
  { id:"song_295", song:"Miss You Much", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_296", song:"Physical", artist:"Dua Lipa", genres:["pop", "dance"] },
  { id:"song_297", song:"Womanizer", artist:"Britney Spears", genres:["diva", "pop", "dance"] },
  { id:"song_298", song:"Phone", artist:"Lizzo", genres:["pop"] },
  { id:"song_299", song:"Dirrty", artist:"Christina Aguilera", genres:["camp", "pop"] },
  { id:"song_300", song:"Dance Again", artist:"Jennifer Lopez feat. Pitbull", genres:["dance", "pop"] },
  { id:"song_301", song:"Sugar Walls", artist:"Sheena Easton", genres:["pop"] },
  { id:"song_302", song:"Boom Clap", artist:"Charli XCX", genres:["hyperpop", "dance"] },
  { id:"song_303", song:"Good Golly Miss Molly", artist:"Little Richard", genres:["pop"] },
  { id:"song_304", song:"Free Your Mind", artist:"En Vogue", genres:["house", "dance", "R&B"] },
  { id:"song_305", song:"Girls Just Wanna Have Fun", artist:"Cyndi Lauper", genres:["camp", "diva"] },
  { id:"song_306", song:"Point of No Return", artist:"Exposé", genres:["dance"] },
  { id:"song_307", song:"Song for the Lonely", artist:"Cher", genres:["pop"] },
  { id:"song_308", song:"Barbie Girl", artist:"Aqua", genres:["camp", "diva"] },
  { id:"song_309", song:"Heartbreaker", artist:"Pat Benatar", genres:["rock"] },
  { id:"song_310", song:"Focus", artist:"Ariana Grande", genres:["pop"] },
  { id:"song_311", song:"Since U Been Gone", artist:"Kelly Clarkson", genres:["pop"] },
  { id:"song_312", song:"Stupid Love", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_313", song:"Livin' La Vida Loca", artist:"Ricky Martin", genres:["Latin", "dance"] },
  { id:"song_314", song:"Neutron Dance", artist:"The Pointer Sisters", genres:["dance"] },
  { id:"song_315", song:"Juice", artist:"Lizzo", genres:["pop"] },
  { id:"song_316", song:"Where Have You Been", artist:"Rihanna", genres:["pop"] },
  { id:"song_317", song:"Open Your Heart", artist:"Madonna", genres:["pop", "dance"] },
  { id:"song_318", song:"One Last Time", artist:"Ariana Grande", genres:["pop"] },
  { id:"song_319", song:"Fancy", artist:"Reba McEntire", genres:["country"] },
  { id:"song_320", song:"Make Me Feel", artist:"Janelle Monáe", genres:["R&B"] },
  { id:"song_321", song:"Emotions", artist:"Mariah Carey", genres:["pop"] },
  { id:"song_322", song:"Into You", artist:"Ariana Grande", genres:["pop"] },
  { id:"song_323", song:"How Will I Know", artist:"Whitney Houston", genres:["R&B"] },
  { id:"song_324", song:"The Bitch is Back", artist:"Tina Turner", genres:["rock", "soul", "funk", "diva"] },
  { id:"song_325", song:"Jump To It", artist:"Aretha Franklin", genres:["R&B", "dance"] },
  { id:"song_326", song:"You Spin Me Round (Like a Record)", artist:"Dead or Alive", genres:["new wave", "pop"] },
  { id:"song_327", song:"Come Rain or Come Shine", artist:"Judy Garland", genres:["ballad", "diva"] },
  { id:"song_328", song:"When I Think of You", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_329", song:"Fighter", artist:"Christina Aguilera", genres:["diva", "pop"] },
  { id:"song_330", song:"Wrecking Ball", artist:"Miley Cyrus", genres:["ballad", "diva", "pop"] },
  { id:"song_331", song:"Shake It Off", artist:"Taylor Swift", genres:["pop"] },
  { id:"song_332", song:"Le Freak (Freak Out)", artist:"Chic", genres:["disco", "dance", "camp"] },
  { id:"song_333", song:"Tell It To My Heart", artist:"Taylor Dayne", genres:["pop"] },
  { id:"song_334", song:"Got To Be Real", artist:"Cheryl Lynn", genres:["disco", "dance", "soul", "funk"] },
  { id:"song_335", song:"Shut Up & Drive", artist:"Rihanna", genres:["pop"] },
  { id:"song_336", song:"Cherry Bomb", artist:"Joan Jett and the Blackhearts", genres:["rock"] },
  { id:"song_337", song:"Step It Up", artist:"RuPaul feat. Dave Audé", genres:["dance"] },
  { id:"song_338", song:"If I Were Your Woman", artist:"Gladys Knight & The Pips", genres:["soul", "funk", "diva"] },
  { id:"song_339", song:"Opposites Attract", artist:"Paula Abdul", genres:["pop", "dance"] },
  { id:"song_340", song:"There's No Business Like Show Business", artist:"Ethel Merman", genres:["theatre", "camp"] },
  { id:"song_341", song:"Nasty", artist:"Janet Jackson", genres:["R&B", "camp", "dance"] },
  { id:"song_342", song:"Don't Cha", artist:"The Pussycat Dolls", genres:["pop", "dance"] },
  { id:"song_343", song:"Dancing On My Own", artist:"Robyn", genres:["pop"] },
  { id:"song_344", song:"Girls on Film", artist:"Duran Duran", genres:["rock", "new wave", "pop", "diva"] },
  { id:"song_345", song:"Don't Call Me Up", artist:"Mabel", genres:["dance"] },
  { id:"song_346", song:"Let's Dance", artist:"David Bowie", genres:["rock", "dance"] },
  { id:"song_347", song:"Something Kinda Ooh", artist:"Girls Aloud", genres:["pop", "dance"] },
  { id:"song_348", song:"Time Warp", artist:"The Cast of The Rocky Horror Picture Show", genres:["theatre", "camp"] },
  { id:"song_349", song:"Never Gonna Give You Up", artist:"Rick Astley", genres:["pop"] },
  { id:"song_350", song:"Crazy What Love Can Do", artist:"David Guetta, Becky Hill, & Elle Henderson", genres:["EDM", "dance"] },
  { id:"song_351", song:"Ooh La La", artist:"Goldfrapp", genres:["alternative"] },
  { id:"song_352", song:"Tension", artist:"Kylie Minogue", genres:["pop", "dance"] },
  { id:"song_353", song:"Hot In It", artist:"Tiësto & Charli XCX", genres:["hyperpop", "EDM", "dance"] },
  { id:"song_354", song:"The Only Way Is Up", artist:"Yazz", genres:["EDM", "dance"] },
  { id:"song_355", song:"I Dreamed A Dream", artist:"Susan Boyle", genres:["ballad", "diva"] },
  { id:"song_356", song:"Heartbreak On Hold", artist:"Alexandra Burke", genres:["dance"] },
  { id:"song_357", song:"Touch Me (I Want Your Body)", artist:"Samantha Fox", genres:["dance"] },
  { id:"song_358", song:"This Hell", artist:"Rina Sawayama", genres:["alternative"] },
  { id:"song_359", song:"Little Bird", artist:"Annie Lenox", genres:["new wave", "pop"] },
  { id:"song_360", song:"Ooh Aah... Just A Little Bit", artist:"Gina G", genres:["pop"] },
  { id:"song_361", song:"Remember", artist:"Becky Hill & David Guetta", genres:["EDM", "dance"] },
  { id:"song_362", song:"Let Them Know", artist:"Mabel", genres:["dance"] },
  { id:"song_363", song:"About You Now", artist:"Sugababes", genres:["pop"] },
  { id:"song_364", song:"This Is Real", artist:"Jax Jones & Ella Henderson", genres:["house", "dance", "EDM"] },
  { id:"song_365", song:"Respectable", artist:"Mel & Kim", genres:["pop"] },
  { id:"song_366", song:"No Way", artist:"Cast of Six feat. Renée Lamb", genres:["theatre", "camp"] },
  { id:"song_367", song:"Stop", artist:"Spice Girls", genres:["pop"] },
  { id:"song_368", song:"Miss Me Blind", artist:"Culture Club", genres:["new wave", "pop"] },
  { id:"song_369", song:"Some Kinda Rush", artist:"Booty Luv", genres:["dance"] },
  { id:"song_370", song:"Another One Bites the Dust", artist:"Queen", genres:["rock"] },
  { id:"song_371", song:"This is My Life", artist:"Shirley Bassey", genres:["ballad", "diva"] },
  { id:"song_372", song:"Sweet Melody", artist:"Little Mix", genres:["pop"] },
  { id:"song_373", song:"Moving On Up", artist:"M People", genres:["house", "dance"] },
  { id:"song_374", song:"I've Got The Music In Me", artist:"The Kiki Dee Band", genres:["rock", "dance"] },
  { id:"song_375", song:"Who Do You Think You Are", artist:"Spice Girls", genres:["pop"] },
  { id:"song_376", song:"Big Spender", artist:"Shirley Bassey", genres:["theatre", "camp"] },
  { id:"song_377", song:"Shout", artist:"Lulu", genres:["pop"] },
  { id:"song_378", song:"Scandalous", artist:"Mis-Teeq", genres:["pop"] },
  { id:"song_379", song:"Hallucinate", artist:"Dua Lipa", genres:["house", "dance", "pop"] },
  { id:"song_380", song:"Total Eclipse of the Heart", artist:"Bonnie Tyler", genres:["ballad", "diva"] },
  { id:"song_381", song:"Something New", artist:"Girls Aloud", genres:["pop", "dance"] },
  { id:"song_382", song:"You Don't Own Me", artist:"Dusty Springfield", genres:["ballad", "diva"] },
  { id:"song_383", song:"Don't Start Now", artist:"Dua Lipa", genres:["house", "dance", "pop"] },
  { id:"song_384", song:"You Keep Me Hangin' On", artist:"Kim Wilde", genres:["new wave", "pop"] },
  { id:"song_385", song:"New Rules", artist:"Dua Lipa", genres:["pop", "dance"] },
  { id:"song_386", song:"Let Me Think About It", artist:"Ida Corr and Fedde Le Grand", genres:["house", "dance", "EDM"] },
  { id:"song_387", song:"What The Hell", artist:"Avril Lavigne", genres:["rock"] },
  { id:"song_388", song:"Hush Hush; Hush Hush", artist:"Pussycat Dolls", genres:["pop", "dance"] },
  { id:"song_389", song:"Hideaway", artist:"Kiesza", genres:["house", "dance"] },
  { id:"song_390", song:"Brand New Bitch", artist:"Anjulie", genres:["diva", "pop"] },
  { id:"song_391", song:"Sk8er Boi", artist:"Avril Lavigne", genres:["rock"] },
  { id:"song_392", song:"Freak", artist:"Estelle (feat. Kardinal Offishall)", genres:["camp", "pop"] },
  { id:"song_393", song:"Mine", artist:"Slayyyter", genres:["hyperpop"] },
  { id:"song_394", song:"Garden of Eden", artist:"Lady Gaga", genres:["rock", "pop", "dance"] },
  { id:"song_395", song:"Super Graphic Ultra Modern Girl", artist:"Chappell Roan", genres:["diva", "pop"] },
  { id:"song_396", song:"Enough (Miami)", artist:"Cardi B", genres:["hip-hop"] },
  { id:"song_397", song:"Too Much", artist:"Dove Cameron", genres:["pop"] },
  { id:"song_398", song:"Symphony", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_399", song:"Midnight Sun", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_400", song:"Pink Pony Club", artist:"Chappell Roan", genres:["dance"] },
  { id:"song_401", song:"Talk talk", artist:"Charli xcx, Troye Sivan", genres:["hyperpop", "dance"] },
  { id:"song_402", song:"The Subway", artist:"Chappell Roan", genres:["ballad", "diva"] },
  { id:"song_403", song:"Gnarly", artist:"KATSEYE", genres:["K-pop", "pop"] },
  { id:"song_404", song:"Zombieboy", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_405", song:"Die with a Smile", artist:"Bruno Mars, Lady Gaga", genres:["ballad", "diva", "pop", "dance"] },
  { id:"song_406", song:"Espresso", artist:"Sabrina Carpenter", genres:["pop"] },
  { id:"song_407", song:"Revolving Door", artist:"Tate Mcrae", genres:["pop"] },
  { id:"song_408", song:"Killah", artist:"Lady Gaga", genres:["rock", "pop", "dance"] },
  { id:"song_409", song:"Perfect Celebrity", artist:"Lady Gaga", genres:["rock", "pop", "dance"] },
  { id:"song_410", song:"Aura", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_411", song:"Donatella", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_412", song:"Sexxx Dreams", artist:"Lady Gaga", genres:["camp", "pop", "dance"] },
  { id:"song_413", song:"Dangerous Woman", artist:"Ariana Grande", genres:["diva", "pop"] },
  { id:"song_414", song:"Tears", artist:"Clean Bandit", genres:["EDM", "dance"] },
  { id:"song_415", song:"Feel Good", artist:"Charlotte Cardin", genres:["pop"] },
  { id:"song_416", song:"It's OK I'm OK", artist:"Tate Mcrae", genres:["pop"] },
  { id:"song_417", song:"Work (Freemasons Radio Edit)", artist:"Kelly Rowland", genres:["dance"] },
  { id:"song_418", song:"U + Ur Hand", artist:"P!nk", genres:["rock", "pop"] },
  { id:"song_419", song:"The Winner Takes It All", artist:"ABBA", genres:["ballad", "diva", "pop"] },
  { id:"song_420", song:"Dancing Queen", artist:"ABBA", genres:["disco", "dance", "diva", "pop"] },
  { id:"song_421", song:"Like a Prayer", artist:"Madonna", genres:["pop", "dance"] },
  { id:"song_422", song:"Hung Up", artist:"Madonna", genres:["disco", "dance", "pop"] },
  { id:"song_423", song:"Deeper and Deeper", artist:"Madonna", genres:["house", "dance", "pop"] },
  { id:"song_424", song:"LoveGame", artist:"Lady Gaga", genres:["dance", "pop"] },
  { id:"song_425", song:"Paparazzi", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_426", song:"Alejandro", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_427", song:"Marry the Night", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_428", song:"G.U.Y.", artist:"Lady Gaga", genres:["pop", "dance"] },
  { id:"song_429", song:"Poker Face", artist:"Lady Gaga", genres:["dance", "pop"] },
  { id:"song_430", song:"Feedback", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_431", song:"Scream", artist:"Michael Jackson", genres:["pop"] },
  { id:"song_432", song:"Lose My Breath", artist:"Destiny's Child", genres:["R&B"] },
  { id:"song_433", song:"Deja Vu", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_434", song:"MY HOUSE", artist:"Beyoncé", genres:["house", "dance", "R&B"] },
  { id:"song_435", song:"We Belong Together", artist:"Mariah Carey", genres:["ballad", "diva"] },
  { id:"song_436", song:"Family Affair", artist:"Mary J. Blige", genres:["R&B"] },
  { id:"song_437", song:"Get Ur Freak On", artist:"Missy Elliott", genres:["hip-hop", "camp"] },
  { id:"song_438", song:"Work It", artist:"Missy Elliott", genres:["hip-hop", "dance"] },
  { id:"song_439", song:"Lose Control", artist:"Missy Elliott", genres:["hip-hop"] },
  { id:"song_440", song:"Misery Business", artist:"Paramore", genres:["rock"] },
  { id:"song_441", song:"My Immortal", artist:"Evanescence", genres:["ballad", "diva"] },
  { id:"song_442", song:"Lovefool", artist:"The Cardigans", genres:["alternative"] },
  { id:"song_443", song:"Let's Have a Kiki", artist:"Scissor Sisters", genres:["camp", "pop"] },
  { id:"song_444", song:"I Don't Feel Like Dancing", artist:"Scissor Sisters", genres:["camp", "pop"] },
  { id:"song_445", song:"Don't Call Me Baby", artist:"Madison Avenue", genres:["house", "dance"] },
  { id:"song_446", song:"She Wolf", artist:"Shakira", genres:["Latin", "dance"] },
  { id:"song_447", song:"Deepthroat", artist:"Cupcakke", genres:["hip-hop", "camp"] },
  { id:"song_448", song:"WAP", artist:"Cardi B", genres:["hip-hop", "camp"] },
  { id:"song_449", song:"B.I.T.C.H.", artist:"Megan Thee Stallion", genres:["hip-hop"] },
  { id:"song_450", song:"Happier Than Ever", artist:"Billie Eilish", genres:["ballad", "diva", "rock", "alternative"] },
  { id:"song_451", song:"Cuntissimo", artist:"MARINA", genres:["alternative"] },
  { id:"song_452", song:"Primadonna", artist:"MARINA", genres:["alternative"] },
  { id:"song_453", song:"Bubblegum Bitch", artist:"MARINA", genres:["alternative", "diva"] },
  { id:"song_454", song:"Froot", artist:"MARINA", genres:["alternative"] },
  { id:"song_455", song:"Call On Me", artist:"Tove Lo", genres:["pop"] },
  { id:"song_456", song:"Disco Tits", artist:"Tove Lo", genres:["disco", "dance", "pop"] },
  { id:"song_457", song:"Moonlight", artist:"Kali Uchis", genres:["pop"] },
  { id:"song_458", song:"Flash Pose", artist:"Pabllo Vittar", genres:["pop"] },
  { id:"song_459", song:"Midnight Sun", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_460", song:"Can't Tame Her", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_461", song:"Lush Life", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_462", song:"Hot & Sexy", artist:"Zara Larsson", genres:["camp", "pop", "dance"] },
  { id:"song_463", song:"Blue Moon", artist:"Zara Larsson", genres:["ballad", "diva", "pop", "dance"] },
  { id:"song_464", song:"Poster Girl", artist:"Zara Larsson", genres:["diva", "pop", "dance"] },
  { id:"song_465", song:"Never Forget You", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_466", song:"Ain't My Fault", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_467", song:"Symphony", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_468", song:"Ruin My Life", artist:"Zara Larsson", genres:["pop", "dance"] },
  { id:"song_469", song:"Freeway of Love", artist:"Aretha Franklin", genres:["R&B"] },
  { id:"song_470", song:"Beautiful Liar", artist:"Beyoncé & Shakira", genres:["Latin", "dance", "R&B"] },
  { id:"song_471", song:"The Way You Make Me Feel", artist:"Michael Jackson", genres:["pop"] },
  { id:"song_472", song:"The Men All Pause", artist:"Klymaxx", genres:["soul", "funk"] },
  { id:"song_473", song:"Is It a Crime?", artist:"Sade", genres:["ballad", "diva", "R&B"] },
  { id:"song_474", song:"The Boy Is Mine", artist:"Brandy & Monica", genres:["R&B"] },
  { id:"song_475", song:"Young Hearts Run Free", artist:"Candi Staton", genres:["disco", "dance", "soul", "funk"] },
  { id:"song_476", song:"Shame", artist:"Evelyn \"Champagne\" King", genres:["disco", "dance", "soul", "funk"] },
  { id:"song_477", song:"Upside Down", artist:"Diana Ross", genres:["disco", "dance", "soul", "funk"] },
  { id:"song_478", song:"Fantastic Voyage", artist:"Lakeside", genres:["soul", "funk"] },
  { id:"song_479", song:"Square Biz", artist:"Teena Marie", genres:["R&B"] },
  { id:"song_480", song:"Take Your Time (Do It Right)", artist:"The S.O.S. Band", genres:["soul", "funk"] },
  { id:"song_481", song:"As", artist:"Stevie Wonder", genres:["soul", "funk"] },
  { id:"song_482", song:"Last Night a DJ Saved My Life", artist:"Indeep", genres:["disco", "dance"] },
  { id:"song_483", song:"She Works Hard for the Money", artist:"Donna Summer", genres:["dance"] },
  { id:"song_484", song:"Ring My Bell", artist:"Anita Ward", genres:["disco", "dance"] },
  { id:"song_485", song:"I Hate Myself for Loving You", artist:"Joan Jett", genres:["rock"] },
  { id:"song_486", song:"Rapture", artist:"Blondie", genres:["rock", "new wave", "pop"] },
  { id:"song_487", song:"Somebody to Love", artist:"Queen", genres:["ballad", "diva", "rock", "dance"] },
  { id:"song_488", song:"What's Love Got to Do with It", artist:"Tina Turner", genres:["ballad", "diva", "soul", "funk"] },
  { id:"song_489", song:"Life on Mars?", artist:"David Bowie", genres:["ballad", "diva", "rock"] },
  { id:"song_490", song:"Ghostbusters", artist:"Ray Parker Jr.", genres:["camp", "pop"] },
  { id:"song_491", song:"Good Ones", artist:"Charli XCX", genres:["hyperpop", "dance"] },
  { id:"song_492", song:"Super Graphic Ultra Modern Girl", artist:"Chappell Roan", genres:["diva", "pop"] },
  { id:"song_493", song:"Frankenstein", artist:"Rina Sawayama", genres:["rock", "alternative"] },
  { id:"song_494", song:"Escapade", artist:"Janet Jackson", genres:["R&B", "dance"] },
  { id:"song_495", song:"Wake Me Up Before You Go-Go", artist:"Wham!", genres:["new wave", "pop"] },
  { id:"song_496", song:"You Drive Me Crazy", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_497", song:"Hollaback Girl", artist:"Gwen Stefani", genres:["diva", "pop"] },
  { id:"song_498", song:"Super Bass", artist:"Nicki Minaj", genres:["hip-hop"] },
  { id:"song_499", song:"Raising Hell", artist:"Kesha & Big Freedia", genres:["hip-hop", "pop"] },
  { id:"song_500", song:"All That Jazz", artist:"(commonly via Chicago)", genres:["theatre", "camp"] },
  { id:"song_501", song:"Candy Store", artist:"(from Heathers / stage versions)", genres:["theatre", "camp"] },
  { id:"song_502", song:"Diamonds Are Forever", artist:"Shirley Bassey", genres:["ballad", "diva"] },
  { id:"song_503", song:"Time After Time", artist:"Cyndi Lauper", genres:["ballad", "diva"] },
  { id:"song_504", song:"I Have Nothing", artist:"Whitney Houston", genres:["ballad", "diva", "R&B"] },
  { id:"song_505", song:"If I Could Turn Back Time", artist:"Cher", genres:["ballad", "diva", "pop"] },
  { id:"song_506", song:"Un-Break My Heart", artist:"Toni Braxton", genres:["ballad", "diva", "R&B"] },
  { id:"song_507", song:"It's Oh So Quiet", artist:"Björk", genres:["theatre", "camp", "alternative"] },
  { id:"song_508", song:"Glory Box", artist:"Portishead", genres:["ballad", "diva", "alternative"] },
  { id:"song_509", song:"Army of Me", artist:"Björk", genres:["rock", "alternative"] },
  { id:"song_510", song:"Venus as a Boy", artist:"Björk", genres:["alternative"] },
  { id:"song_511", song:"Pagan Poetry", artist:"Björk", genres:["ballad", "diva", "alternative"] },
  { id:"song_512", song:"Tear Me Down", artist:"Grace Jones", genres:["theatre", "camp", "EDM", "dance"] },
  { id:"song_513", song:"Fergalicious", artist:"Fergie", genres:["pop"] },
  { id:"song_514", song:"Hella Good", artist:"No Doubt", genres:["rock"] },
  { id:"song_515", song:"Spinning Around", artist:"Kylie Minogue", genres:["disco", "dance", "pop"] },
  { id:"song_516", song:"XS", artist:"Rina Sawayama", genres:["rock", "alternative"] },
  { id:"song_517", song:"Does Your Mother Know", artist:"ABBA", genres:["disco", "dance", "pop"] },
  { id:"song_518", song:"The Ladies Who Lunch", artist:"Elaine Stritch", genres:["theatre", "camp"] },
  { id:"song_519", song:"Somewhere That's Green", artist:"Little Shop of Horrors", genres:["theatre", "camp"] },
  { id:"song_520", song:"Potential Breakup Song", artist:"Aly & AJ", genres:["rock"] },
  { id:"song_521", song:"Timebomb", artist:"Kylie Minogue", genres:["pop", "dance"] },
  { id:"song_522", song:"Love Machine", artist:"Girls Aloud", genres:["pop", "dance"] },
  { id:"song_523", song:"Parachute", artist:"Cheryl", genres:["pop"] },
  { id:"song_524", song:"Chacarron", artist:"El Chombo", genres:["camp", "Latin", "dance"] },
  { id:"song_525", song:"Bad Girls", artist:"M.I.A.", genres:["hip-hop", "diva"] },
  { id:"song_526", song:"Black Lake", artist:"Björk", genres:["ballad", "diva", "alternative"] },
  { id:"song_527", song:"Born Again", artist:"LISA feat. RAYE", genres:["K-pop", "pop"] },
  { id:"song_528", song:"Hot Stuff", artist:"Donna Summer", genres:["disco", "dance"] },
  { id:"song_529", song:"It's a Heartache", artist:"Bonnie Tyler", genres:["ballad", "diva"] },
  { id:"song_530", song:"Oh No!", artist:"MARINA", genres:["alternative"] },
  { id:"song_531", song:"Umbrella", artist:"Rihanna", genres:["pop"] },
  { id:"song_532", song:"Leave Me Alone", artist:"Reneé Rapp", genres:["rock"] },
  { id:"song_533", song:"At Last", artist:"Etta James", genres:["ballad", "diva", "soul", "funk"] },
  { id:"song_534", song:"Somewhere Over the Rainbow", artist:"Judy Garland", genres:["ballad", "diva"] },
  { id:"song_535", song:"I Never Loved a Man (The Way I Love You)", artist:"Aretha Franklin", genres:["ballad", "diva", "R&B"] },
  { id:"song_536", song:"The Power of Love", artist:"Céline Dion", genres:["ballad", "diva"] },
  { id:"song_537", song:"16 Carriages", artist:"Beyoncé", genres:["country", "R&B"] },
  { id:"song_538", song:"Night Fever", artist:"Bee Gees", genres:["disco", "dance"] },
  { id:"song_539", song:"Goldfinger", artist:"Shirley Bassey", genres:["theatre", "camp"] },
  { id:"song_540", song:"Hopelessly Devoted to You", artist:"Olivia Newton-John", genres:["ballad", "diva"] },
  { id:"song_541", song:"Spectrum (Calvin Harris Remix)", artist:"Florence + the Machine / Calvin Harris", genres:["alternative"] },
  { id:"song_542", song:"Dog Days Are Over", artist:"Florence + the Machine", genres:["rock", "alternative"] },
  { id:"song_543", song:"1, 2 Step", artist:"Ciara", genres:["R&B"] },
  { id:"song_544", song:"Like a Boy", artist:"Ciara", genres:["R&B"] },
  { id:"song_545", song:"Proud Mary", artist:"Ike & Tina Turner", genres:["rock", "soul", "funk"] },
  { id:"song_546", song:"I'm Just a Girl", artist:"No Doubt", genres:["rock", "diva"] },
  { id:"song_547", song:"Alone", artist:"Heart", genres:["ballad", "diva", "rock"] },
  { id:"song_548", song:"Barracuda", artist:"Heart", genres:["rock"] },
  { id:"song_549", song:"Gypsy Woman (She's Homeless)", artist:"Crystal Waters", genres:["disco", "dance", "diva"] },
  { id:"song_550", song:"Last Friday Night (T.G.I.F.)", artist:"Katy Perry", genres:["pop"] },
  { id:"song_551", song:"Waterfalls", artist:"TLC", genres:["ballad", "diva", "R&B"] },
  { id:"song_552", song:"Wannabe", artist:"Spice Girls", genres:["camp", "pop"] },
  { id:"song_553", song:"Wuthering Heights", artist:"Kate Bush", genres:["rock", "alternative"] },
  { id:"song_554", song:"Get the Party Started", artist:"P!nk", genres:["dance", "pop"] },
  { id:"song_555", song:"Broken Heels", artist:"Alexandra Burke", genres:["dance"] },
  { id:"song_556", song:"The Boy Does Nothing", artist:"Alesha Dixon", genres:["pop"] },
  { id:"song_557", song:"The Promise", artist:"Girls Aloud", genres:["pop", "dance"] },
  { id:"song_558", song:"Notorious", artist:"The Saturdays", genres:["pop"] },
  { id:"song_559", song:"Up", artist:"The Saturdays", genres:["pop"] },
  { id:"song_560", song:"Wasabi", artist:"Little Mix", genres:["pop"] },
  { id:"song_561", song:"Fight for This Love", artist:"Cheryl", genres:["pop"] },
  { id:"song_562", song:"Hello", artist:"Adele", genres:["ballad", "diva"] },
  { id:"song_563", song:"Boom Bang-a-Bang", artist:"Lulu", genres:["theatre", "camp"] },
  { id:"song_564", song:"Don't Forget to Sir, With Love", artist:"Lulu", genres:["ballad", "diva"] },
  { id:"song_565", song:"Mercy", artist:"Duffy", genres:["pop"] },
  { id:"song_566", song:"Goodbye Yellow Brick Road", artist:"Elton John", genres:["ballad", "diva"] },
  { id:"song_567", song:"Swagger Jagger", artist:"Cher Lloyd", genres:["camp", "pop"] },
  { id:"song_568", song:"Vroom Vroom", artist:"Charli XCX", genres:["hyperpop", "dance"] },
  { id:"song_569", song:"Ain't Nobody", artist:"Chaka Khan", genres:["soul", "funk", "dance"] },
  { id:"song_570", song:"Kiss Me More", artist:"Doja Cat ft. SZA", genres:["pop"] },
  { id:"song_571", song:"Back to Black", artist:"Amy Winehouse", genres:["ballad", "diva", "rock"] },
  { id:"song_572", song:"Let Yourself Go", artist:"The Supremes", genres:["soul", "funk"] },
  { id:"song_573", song:"Goodies", artist:"Ciara", genres:["R&B"] },
  { id:"song_574", song:"Little Red Corvette", artist:"Prince", genres:["soul", "funk"] },
  { id:"song_575", song:"When Doves Cry", artist:"Prince", genres:["soul", "funk"] },
  { id:"song_576", song:"Super Bad", artist:"James Brown", genres:["soul", "funk"] },
  { id:"song_577", song:"I'll Take You There", artist:"The Staple Singers", genres:["soul", "funk"] },
  { id:"song_578", song:"American Boy", artist:"Estelle", genres:["pop"] },
  { id:"song_579", song:"I Feel for You", artist:"Chaka Khan", genres:["soul", "funk"] },
  { id:"song_580", song:"I'm Every Woman", artist:"Whitney Houston", genres:["R&B", "diva"] },
  { id:"song_581", song:"Voulez-Vous", artist:"ABBA", genres:["disco", "dance", "pop"] },
  { id:"song_582", song:"Countdown", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_583", song:"Beat It", artist:"Michael Jackson", genres:["rock", "dance"] },
  { id:"song_584", song:"Circus", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_585", song:"Do Somethin'", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_586", song:"Die Young", artist:"Kesha", genres:["pop"] },
  { id:"song_587", song:"Feather", artist:"Sabrina Carpenter", genres:["pop"] },
  { id:"song_588", song:"My Oh My", artist:"Ava Max", genres:["pop", "dance"] },
  { id:"song_589", song:"Unstoppable", artist:"Kylie Minogue", genres:["pop", "dance"] },
  { id:"song_590", song:"Can't Get You Out of My Head", artist:"Kylie Minogue", genres:["disco", "dance", "pop"] },
  { id:"song_591", song:"Turn Me On", artist:"David Guetta ft. Nicki Minaj", genres:["EDM", "dance", "hip-hop"] },
  { id:"song_592", song:"Houdini", artist:"Dua Lipa", genres:["pop", "dance"] },
  { id:"song_593", song:"Rose's Turn", artist:"Gypsy", genres:["theatre", "camp"] },
  { id:"song_594", song:"Commander", artist:"Kelly Rowland", genres:["house", "dance", "diva"] },
  { id:"song_595", song:"Sweet But Psycho", artist:"Ava Max", genres:["dance", "pop"] },
  { id:"song_596", song:"Walking On Air", artist:"Katy Perry", genres:["house", "dance", "pop"] },
  { id:"song_597", song:"React", artist:"The Pussycat Dolls", genres:["dance", "pop"] },
  { id:"song_598", song:"Poison", artist:"Nicole Scherzinger", genres:["dance", "pop"] },
  { id:"song_599", song:"Bad Girl", artist:"Danity Kane feat. Missy Elliott", genres:["R&B", "hip-hop", "diva"] },
  { id:"song_600", song:"What You Waiting For?", artist:"Gwen Stefani", genres:["camp", "pop"] },
  { id:"song_601", song:"Woman", artist:"Kesha", genres:["diva", "pop"] },
  { id:"song_602", song:"Piece of Me", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_603", song:"Conga", artist:"Gloria Estefan", genres:["Latin", "dance", "pop"] },
  { id:"song_604", song:"All About That Bass", artist:"Meghan Trainor", genres:["camp", "pop"] },
  { id:"song_605", song:"Nutbush City Limits", artist:"Tina Turner", genres:["soul", "rock", "funk"] },
  { id:"song_606", song:"A Thousand Miles", artist:"Vanessa Carlton", genres:["camp", "pop"] },
  { id:"song_607", song:"It’s Not Right, But It’s Okay", artist:"Whitney Houston", genres:["R&B", "diva"] },
  { id:"song_608", song:"Kitty Kat", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_609", song:"Doesn’t Really Matter", artist:"Janet Jackson", genres:["dance", "pop", "R&B"] },
  { id:"song_610", song:"Roman’s Revenge", artist:"Nicki Minaj", genres:["theatre", "camp", "hip-hop"] },
  { id:"song_611", song:"ICY GRL", artist:"Saweetie", genres:["hip-hop"] },
  { id:"song_612", song:"Chun-Li", artist:"Nicki Minaj", genres:["hip-hop"] },
  { id:"song_613", song:"Company", artist:"Tinashe", genres:["dance", "R&B"] },
  { id:"song_614", song:"Wash & Set", artist:"Leikeli47", genres:["camp", "hip-hop"] },
  { id:"song_615", song:"Love on Top", artist:"Beyoncé", genres:["R&B", "diva", "pop"] },
  { id:"song_616", song:"Swalla", artist:"Jason Derulo feat. Nicki Minaj & Ty Dolla $ign", genres:["house", "dance", "hip-hop", "pop"] },
  { id:"song_617", song:"Good Form", artist:"Nicki Minaj", genres:["hip-hop"] },
  { id:"song_618", song:"Don’t Hurt Yourself", artist:"Beyoncé feat. Jack White", genres:["R&B", "rock"] },
  { id:"song_619", song:"Love on the Brain", artist:"Rihanna", genres:["ballad", "soul", "pop"] },
  { id:"song_620", song:"Wild Thoughts", artist:"DJ Khaled feat. Rihanna & Bryson Tiller", genres:["Latin", "R&B", "pop", "dance"] },
  { id:"song_621", song:"Gimme More", artist:"Britney Spears", genres:["dance", "pop"] },
  { id:"song_622", song:"How to Be a Heartbreaker", artist:"MARINA", genres:["camp", "pop", "alternative"] },
  { id:"song_623", song:"Babylon", artist:"Lady Gaga", genres:["house", "dance", "pop"] },
  { id:"song_624", song:"Don’t Stop Me Now", artist:"Queen", genres:["rock"] },
  { id:"song_625", song:"Latch", artist:"Disclosure feat. Sam Smith", genres:["house", "dance", "EDM"] },
  { id:"song_626", song:"Birthday", artist:"Katy Perry", genres:["camp", "pop"] },
  { id:"song_627", song:"Boys", artist:"Lizzo", genres:["funk", "pop"] },
  { id:"song_628", song:"Teenage Dream", artist:"Katy Perry", genres:["pop"] },
  { id:"song_629", song:"…Baby One More Time", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_630", song:"Comme des Garçons (Like the Boys)", artist:"Rina Sawayama", genres:["dance", "pop", "alternative"] },
  { id:"song_631", song:"Walking on Broken Glass", artist:"Annie Lennox", genres:["theatre", "camp", "pop", "new wave"] },
  { id:"song_632", song:"Band of Gold", artist:"Freda Payne", genres:["soul", "pop"] },
  { id:"song_633", song:"What Have You Done for Me Lately", artist:"Janet Jackson", genres:["dance", "R&B"] },
  { id:"song_634", song:"Battlefield", artist:"Jordin Sparks", genres:["pop"] },
  { id:"song_635", song:"Feels Like I’m in Love", artist:"Kelly Marie", genres:["disco", "dance"] },
  { id:"song_636", song:"Domino", artist:"Jessie J", genres:["dance", "pop"] },
  { id:"song_637", song:"Turn It Out", artist:"Patti LaBelle", genres:["dance", "soul", "diva", "funk"] },
  { id:"song_638", song:"Free Yourself", artist:"Chaka Khan", genres:["house", "dance", "soul", "diva"] },
  { id:"song_639", song:"What’s Up?", artist:"4 Non Blondes", genres:["rock"] },
  { id:"song_640", song:"Edge of Seventeen", artist:"Stevie Nicks", genres:["rock"] },
  { id:"song_641", song:"Mother’s Daughter", artist:"Miley Cyrus", genres:["rock", "pop"] },
  { id:"song_642", song:"Hard Times", artist:"Paramore", genres:["rock", "pop"] },
  { id:"song_643", song:"Don’t Speak", artist:"No Doubt", genres:["ballad", "rock"] },
  { id:"song_644", song:"Cruel Summer", artist:"Taylor Swift", genres:["diva", "pop"] },
  { id:"song_645", song:"In My Arms", artist:"Kylie Minogue", genres:["dance", "pop"] },
  { id:"song_646", song:"Bitch I’m Madonna", artist:"Madonna feat. Nicki Minaj", genres:["camp", "dance", "pop", "hip-hop"] },
  { id:"song_647", song:"America Has a Problem", artist:"Beyoncé", genres:["dance", "R&B"] },
  { id:"song_648", song:"Pink Diamond", artist:"Charli XCX", genres:["hyperpop", "dance", "pop"] },
  { id:"song_649", song:"Everything Is Embarrassing", artist:"Sky Ferreira", genres:["alternative", "pop"] },
  { id:"song_650", song:"Genie in a Bottle", artist:"Christina Aguilera", genres:["R&B", "pop"] },
  { id:"song_651", song:"Come to Me", artist:"France Joli", genres:["disco", "dance"] },
  { id:"song_652", song:"Mr. Saxobeat", artist:"Alexandra Stan", genres:["EDM", "dance"] },
  { id:"song_653", song:"The Sign", artist:"Ace of Base", genres:["pop"] },
  { id:"song_654", song:"Say You’ll Be There", artist:"Spice Girls", genres:["pop"] },
  { id:"song_655", song:"More, More, More", artist:"Andrea True Connection", genres:["camp", "disco", "dance"] },
  { id:"song_656", song:"Immaterial", artist:"SOPHIE", genres:["hyperpop", "dance", "house", "pop"] },
  { id:"song_657", song:"I’d Do Anything for Love (But I Won’t Do That)", artist:"Meat Loaf", genres:["theatre", "camp", "rock"] },
  { id:"song_658", song:"Still Into You", artist:"Paramore", genres:["rock", "pop"] },
  { id:"song_659", song:"Dragostea Din Tei", artist:"O-Zone", genres:["camp", "EDM", "dance"] },
  { id:"song_660", song:"Just Fine", artist:"Mary J. Blige", genres:["R&B"] },
  { id:"song_661", song:"Keep This Fire Burning", artist:"Robyn", genres:["dance", "pop"] },
  { id:"song_662", song:"Breakin’ Dishes", artist:"Rihanna", genres:["R&B", "pop"] },
  { id:"song_663", song:"Don’t Stop the Music", artist:"Rihanna", genres:["house", "dance", "pop"] },
  { id:"song_664", song:"Rich Girl", artist:"Gwen Stefani feat. Eve", genres:["camp", "hip-hop", "pop", "diva"] },
  { id:"song_665", song:"The Best", artist:"Tina Turner", genres:["diva", "pop", "soul", "funk"] },
  { id:"song_666", song:"Free", artist:"Ultra Naté", genres:["house", "dance", "pop"] },
  { id:"song_667", song:"Untouched", artist:"The Veronicas", genres:["rock", "pop"] },
  { id:"song_668", song:"Lip Gloss", artist:"Lil Mama", genres:["camp", "hip-hop"] },
  { id:"song_669", song:"Gloria", artist:"Laura Branigan", genres:["diva", "pop"] },
  { id:"song_670", song:"Burnin’ Up", artist:"Jessie J", genres:["dance", "pop"] },
  { id:"song_671", song:"The One That Got Away", artist:"Katy Perry", genres:["pop"] },
  { id:"song_672", song:"9 to 5", artist:"Dolly Parton", genres:["camp", "country", "pop"] },
  { id:"song_673", song:"God Is a Woman", artist:"Ariana Grande", genres:["R&B", "pop", "diva"] },
  { id:"song_674", song:"Like a Girl", artist:"Lizzo", genres:["diva", "pop"] },
  { id:"song_675", song:"According to You", artist:"Orianthi", genres:["rock", "pop"] },
  { id:"song_676", song:"Boots", artist:"Kesha", genres:["camp", "dance", "pop"] },
  { id:"song_677", song:"Shoop", artist:"Salt-N-Pepa", genres:["hip-hop"] },
  { id:"song_678", song:"Gimme! Gimme! Gimme! (A Man After Midnight)", artist:"ABBA", genres:["disco", "dance", "pop"] },
  { id:"song_679", song:"Lay All Your Love On Me", artist:"ABBA", genres:["disco", "dance", "pop"] },
  { id:"song_680", song:"Mamma Mia", artist:"ABBA", genres:["camp", "pop"] },
  { id:"song_681", song:"Rolling in the Deep", artist:"Adele", genres:["soul", "pop"] },
  { id:"song_682", song:"Someone Like You", artist:"Adele", genres:["ballad", "pop"] },
  { id:"song_683", song:"Bad Boys", artist:"Alexandra Burke feat. Flo Rida", genres:["dance", "pop"] },
  { id:"song_684", song:"Boy, You Can Keep It", artist:"Alex Newell", genres:["theatre", "camp", "dance", "diva"] },
  { id:"song_685", song:"Girl On Fire", artist:"Alicia Keys", genres:["ballad", "diva", "R&B"] },
  { id:"song_686", song:"If I Ain’t Got You", artist:"Alicia Keys", genres:["ballad", "R&B"] },
  { id:"song_687", song:"Me & Mr Jones", artist:"Amy Winehouse", genres:["soul"] },
  { id:"song_688", song:"Rehab", artist:"Amy Winehouse", genres:["soul", "pop"] },
  { id:"song_689", song:"Bloodline", artist:"Ariana Grande", genres:["dance", "R&B", "pop"] },
  { id:"song_690", song:"Positions", artist:"Ariana Grande", genres:["R&B", "pop"] },
  { id:"song_691", song:"Side to Side", artist:"Ariana Grande feat. Nicki Minaj", genres:["R&B", "pop", "hip-hop"] },
  { id:"song_692", song:"212", artist:"Azealia Banks feat. Lazy Jay", genres:["house", "dance", "hip-hop"] },
  { id:"song_693", song:"Yes Sir, I Can Boogie", artist:"Baccara", genres:["camp", "disco", "dance"] },
  { id:"song_694", song:"Don’t Rain on My Parade", artist:"Barbra Streisand", genres:["theatre", "camp", "diva"] },
  { id:"song_695", song:"Stayin’ Alive", artist:"Bee Gees", genres:["disco", "dance"] },
  { id:"song_696", song:"Heaven Is a Place on Earth", artist:"Belinda Carlisle", genres:["pop"] },
  { id:"song_697", song:"7/11", artist:"Beyoncé", genres:["dance", "R&B"] },
  { id:"song_698", song:"Crazy in Love", artist:"Beyoncé feat. Jay-Z", genres:["R&B", "pop"] },
  { id:"song_699", song:"Diva", artist:"Beyoncé", genres:["R&B", "diva"] },
  { id:"song_700", song:"Halo", artist:"Beyoncé", genres:["ballad", "R&B"] },
  { id:"song_701", song:"Naughty Girl", artist:"Beyoncé", genres:["R&B", "pop", "diva"] },
  { id:"song_702", song:"Ring the Alarm", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_703", song:"Run the World (Girls)", artist:"Beyoncé", genres:["dance", "R&B", "diva"] },
  { id:"song_704", song:"Video Phone", artist:"Beyoncé", genres:["R&B"] },
  { id:"song_705", song:"I Love Men", artist:"Eartha Kitt", genres:["camp", "dance"] },
  { id:"song_706", song:"Criminal", artist:"Britney Spears", genres:["pop", "dance"] },
  { id:"song_707", song:"Bette Davis Eyes", artist:"Kim Carnes", genres:["pop"] },
  { id:"song_708", song:"You Think You’re a Man", artist:"Divine", genres:["camp", "disco", "dance", "pop"] },
  { id:"song_709", song:"Stand Back", artist:"Stevie Nicks", genres:["dance", "rock"] },
  { id:"song_710", song:"Don’t Wanna Fall in Love", artist:"Jane Child", genres:["dance", "pop"] },
  { id:"song_711", song:"Cupid (Twin Version)", artist:"FIFTY FIFTY", genres:["K-pop", "pop"] },
  { id:"song_712", song:"My Heart Will Go On", artist:"Céline Dion", genres:["ballad", "pop"] },
  { id:"song_713", song:"Bad Boy", artist:"Cascada", genres:["EDM", "dance"] },
  { id:"song_714", song:"Babooshka", artist:"Kate Bush", genres:["camp", "alternative", "pop"] },
  { id:"song_715", song:"Boys Boys Boys", artist:"Lady Gaga", genres:["house", "dance", "pop"] },
  { id:"song_716", song:"When I Hear Music", artist:"Debbie Deb", genres:["house", "dance"] },
  { id:"song_717", song:"Ready for It?", artist:"Taylor Swift", genres:["pop"] },
  { id:"song_718", song:"Just a Touch of Love", artist:"C+C Music Factory", genres:["house", "dance"] },
  { id:"song_719", song:"Pynk", artist:"Janelle Monáe", genres:["R&B", "alternative", "pop"] },
  { id:"song_720", song:"Raspberry Beret", artist:"Prince", genres:["K-pop", "pop", "funk", "soul"] },
  { id:"song_721", song:"Not Myself Tonight", artist:"Christina Aguilera", genres:["dance", "pop"] },
  { id:"song_722", song:"Case of the Ex", artist:"Mýa", genres:["R&B"] },
  { id:"song_723", song:"Gold Dust", artist:"DJ Fresh", genres:["EDM", "dance"] },
  { id:"song_724", song:"The Right Song", artist:"Tiësto & Oliver Heldens", genres:["EDM", "dance"] },
  { id:"song_725", song:"Like That", artist:"Doja Cat feat. Gucci Mane", genres:["hip-hop", "pop"] },
  { id:"song_726", song:"Rules", artist:"Doja Cat", genres:["hip-hop", "pop"] },
  { id:"song_727", song:"Dance for Me", artist:"ALMA", genres:["dance", "pop"] },
  { id:"song_728", song:"Starring Role", artist:"MARINA", genres:["theatre", "camp", "pop", "alternative"] },
  { id:"song_729", song:"Waterloo", artist:"ABBA", genres:["camp", "pop"] },
  { id:"song_730", song:"Slave 4 U", artist:"Britney Spears", genres:["dance", "pop"] },
  { id:"song_731", song:"Candy", artist:"Mandy Moore", genres:["pop"] },
  { id:"song_732", song:"Whip It", artist:"Devo", genres:["camp", "new wave", "pop"] },
  { id:"song_733", song:"Va Va Voom", artist:"Nicki Minaj", genres:["hip-hop", "pop"] },
  { id:"song_734", song:"Girlfriend", artist:"Avril Lavigne", genres:["rock", "pop", "diva"] },
  { id:"song_735", song:"High Horse", artist:"Kacey Musgraves", genres:["country", "disco", "dance"] },
  { id:"song_736", song:"Kill V. Maim", artist:"Grimes", genres:["pop", "alternative"] },
  { id:"song_737", song:"Maneater", artist:"Nelly Furtado", genres:["R&B", "pop"] },
  { id:"song_738", song:"On the Radio", artist:"Donna Summer", genres:["disco", "dance", "pop"] },
  { id:"song_739", song:"Part of Me", artist:"Katy Perry", genres:["dance", "pop"] },
  { id:"song_740", song:"Like a Virgin", artist:"Madonna", genres:["pop", "dance"] },
  { id:"song_741", song:"No Angel", artist:"Charli XCX", genres:["pop", "hyperpop", "dance"] },
  { id:"song_742", song:"Brokenhearted", artist:"Karmin", genres:["hip-hop", "pop"] },
  { id:"song_743", song:"Come Back to Me", artist:"Vanessa Hudgens", genres:["dance", "pop"] },
  { id:"song_744", song:"Smalltown Boy", artist:"Bronski Beat", genres:["new wave", "pop"] },
  { id:"song_745", song:"Systemagic", artist:"Goldfrapp", genres:["alternative"] },
  { id:"song_746", song:"Criminal", artist:"Fiona Apple", genres:["alternative", "pop"] },
  { id:"song_747", song:"Hyperballad", artist:"Björk", genres:["alternative", "pop"] },
  { id:"song_748", song:"Blind", artist:"Hercules and Love Affair", genres:["house", "dance"] }
];
