window.LIPSYNC_PERFORMANCE_COMMENT_GENRES = [
  "pop",
  "dance",
  "EDM",
  "house",
  "disco",
  "R&B",
  "soul",
  "funk",
  "hip-hop",
  "rock",
  "ballad",
  "camp",
  "theatre",
  "country",
  "Latin",
  "K-pop",
  "alternative",
  "hyperpop",
  "new wave",
  "diva"
];

window.LIPSYNC_PERFORMANCE_COMMENTS = {
  "pop": {
    "good": [
      "{Name} locks into the pop beat immediately and sells the song with bright pop-star confidence.",
      "{Name} catches every catchy lyric, making the performance feel polished and fully lived-in.",
      "{Name} turns the chorus hook into a clear highlight and keeps the judges watching.",
      "{Name} uses clean pop choreography without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the big chorus moment.",
      "{Name} understands the song’s glossy pop polish and makes every expression feel intentional.",
      "{Name} commands the stage with sparkly radio-ready energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the pop beat with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the chorus hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the big chorus moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the glossy pop polish of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the pop beat, making the performance feel disconnected from the track.",
      "{Name} misses every catchy lyric, so the number loses the flavor that this genre needs.",
      "{Name} underplays the chorus hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts clean pop choreography, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the big chorus moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s glossy pop polish, giving choices that feel generic.",
      "{Name} starts with promise, but the sparkly radio-ready energy fades before the song really takes off.",
      "{Name} falls behind the pop beat, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the chorus hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the big chorus moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "dance": {
    "good": [
      "{Name} locks into the dance beat immediately and sells the song with unstoppable dance-floor confidence.",
      "{Name} catches every rhythm change, making the performance feel polished and fully lived-in.",
      "{Name} turns the floor-filling hook into a clear highlight and keeps the judges watching.",
      "{Name} uses sharp club choreography without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the peak dance break.",
      "{Name} understands the song’s sweaty club intensity and makes every expression feel intentional.",
      "{Name} commands the stage with high-energy club power, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the dance beat with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the floor-filling hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the peak dance break, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the sweaty club intensity of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the dance beat, making the performance feel disconnected from the track.",
      "{Name} misses every rhythm change, so the number loses the flavor that this genre needs.",
      "{Name} underplays the floor-filling hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts sharp club choreography, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the peak dance break, so the performance stays flat.",
      "{Name} seems unsure of the song’s sweaty club intensity, giving choices that feel generic.",
      "{Name} starts with promise, but the high-energy club power fades before the song really takes off.",
      "{Name} falls behind the dance beat, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the floor-filling hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the peak dance break, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "EDM": {
    "good": [
      "{Name} locks into the electronic pulse immediately and sells the song with festival-stage command.",
      "{Name} catches every build and drop, making the performance feel polished and fully lived-in.",
      "{Name} turns the massive drop into a clear highlight and keeps the judges watching.",
      "{Name} uses explosive beat-driven movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the drop moment.",
      "{Name} understands the song’s electronic impact and makes every expression feel intentional.",
      "{Name} commands the stage with strobe-lit EDM energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the electronic pulse with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the massive drop with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the drop moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the electronic impact of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the electronic pulse, making the performance feel disconnected from the track.",
      "{Name} misses every build and drop, so the number loses the flavor that this genre needs.",
      "{Name} underplays the massive drop, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts explosive beat-driven movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the drop moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s electronic impact, giving choices that feel generic.",
      "{Name} starts with promise, but the strobe-lit EDM energy fades before the song really takes off.",
      "{Name} falls behind the electronic pulse, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the massive drop, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the drop moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "house": {
    "good": [
      "{Name} locks into the house groove immediately and sells the song with after-hours confidence.",
      "{Name} catches every pulse of the rhythm, making the performance feel polished and fully lived-in.",
      "{Name} turns the deep club hook into a clear highlight and keeps the judges watching.",
      "{Name} uses loose but controlled house movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the groove pocket.",
      "{Name} understands the song’s warm house flow and makes every expression feel intentional.",
      "{Name} commands the stage with steady ballroom-club energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the house groove with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the deep club hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the groove pocket, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the warm house flow of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the house groove, making the performance feel disconnected from the track.",
      "{Name} misses every pulse of the rhythm, so the number loses the flavor that this genre needs.",
      "{Name} underplays the deep club hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts loose but controlled house movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the groove pocket, so the performance stays flat.",
      "{Name} seems unsure of the song’s warm house flow, giving choices that feel generic.",
      "{Name} starts with promise, but the steady ballroom-club energy fades before the song really takes off.",
      "{Name} falls behind the house groove, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the deep club hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the groove pocket, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "disco": {
    "good": [
      "{Name} locks into the disco groove immediately and sells the song with sparkling dance-floor charisma.",
      "{Name} catches every bassline accent, making the performance feel polished and fully lived-in.",
      "{Name} turns the glittering disco hook into a clear highlight and keeps the judges watching.",
      "{Name} uses throwback disco movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the disco breakdown.",
      "{Name} understands the song’s retro sparkle and makes every expression feel intentional.",
      "{Name} commands the stage with glittery Saturday-night energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the disco groove with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the glittering disco hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the disco breakdown, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the retro sparkle of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the disco groove, making the performance feel disconnected from the track.",
      "{Name} misses every bassline accent, so the number loses the flavor that this genre needs.",
      "{Name} underplays the glittering disco hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts throwback disco movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the disco breakdown, so the performance stays flat.",
      "{Name} seems unsure of the song’s retro sparkle, giving choices that feel generic.",
      "{Name} starts with promise, but the glittery Saturday-night energy fades before the song really takes off.",
      "{Name} falls behind the disco groove, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the glittering disco hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the disco breakdown, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "R&B": {
    "good": [
      "{Name} locks into the R&B groove immediately and sells the song with cool R&B confidence.",
      "{Name} catches every vocal run and lyric, making the performance feel polished and fully lived-in.",
      "{Name} turns the smooth vocal hook into a clear highlight and keeps the judges watching.",
      "{Name} uses sensual controlled movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the vocal attitude moment.",
      "{Name} understands the song’s smooth R&B finesse and makes every expression feel intentional.",
      "{Name} commands the stage with sultry groove-driven energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the R&B groove with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the smooth vocal hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the vocal attitude moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the smooth R&B finesse of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the R&B groove, making the performance feel disconnected from the track.",
      "{Name} misses every vocal run and lyric, so the number loses the flavor that this genre needs.",
      "{Name} underplays the smooth vocal hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts sensual controlled movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the vocal attitude moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s smooth R&B finesse, giving choices that feel generic.",
      "{Name} starts with promise, but the sultry groove-driven energy fades before the song really takes off.",
      "{Name} falls behind the R&B groove, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the smooth vocal hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the vocal attitude moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "soul": {
    "good": [
      "{Name} locks into the soulful rhythm immediately and sells the song with raw emotional command.",
      "{Name} catches every heartfelt lyric, making the performance feel polished and fully lived-in.",
      "{Name} turns the emotional refrain into a clear highlight and keeps the judges watching.",
      "{Name} uses grounded soulful movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the big emotional release.",
      "{Name} understands the song’s classic soul feeling and makes every expression feel intentional.",
      "{Name} commands the stage with warm soul power, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the soulful rhythm with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the emotional refrain with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the big emotional release, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the classic soul feeling of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the soulful rhythm, making the performance feel disconnected from the track.",
      "{Name} misses every heartfelt lyric, so the number loses the flavor that this genre needs.",
      "{Name} underplays the emotional refrain, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts grounded soulful movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the big emotional release, so the performance stays flat.",
      "{Name} seems unsure of the song’s classic soul feeling, giving choices that feel generic.",
      "{Name} starts with promise, but the warm soul power fades before the song really takes off.",
      "{Name} falls behind the soulful rhythm, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the emotional refrain, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the big emotional release, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "funk": {
    "good": [
      "{Name} locks into the funk pocket immediately and sells the song with playful funk swagger.",
      "{Name} catches every bass hit and groove accent, making the performance feel polished and fully lived-in.",
      "{Name} turns the bassline hook into a clear highlight and keeps the judges watching.",
      "{Name} uses syncopated funk movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the bassline break.",
      "{Name} understands the song’s groovy funk flavor and makes every expression feel intentional.",
      "{Name} commands the stage with rubber-band funk energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the funk pocket with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the bassline hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the bassline break, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the groovy funk flavor of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the funk pocket, making the performance feel disconnected from the track.",
      "{Name} misses every bass hit and groove accent, so the number loses the flavor that this genre needs.",
      "{Name} underplays the bassline hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts syncopated funk movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the bassline break, so the performance stays flat.",
      "{Name} seems unsure of the song’s groovy funk flavor, giving choices that feel generic.",
      "{Name} starts with promise, but the rubber-band funk energy fades before the song really takes off.",
      "{Name} falls behind the funk pocket, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the bassline hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the bassline break, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "hip-hop": {
    "good": [
      "{Name} locks into the hip-hop beat immediately and sells the song with unbothered rap-star swagger.",
      "{Name} catches every bar and ad-lib, making the performance feel polished and fully lived-in.",
      "{Name} turns the rap hook into a clear highlight and keeps the judges watching.",
      "{Name} uses hard-hitting hip-hop movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the verse punchline.",
      "{Name} understands the song’s sharp lyrical attack and makes every expression feel intentional.",
      "{Name} commands the stage with commanding streetwise energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the hip-hop beat with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the rap hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the verse punchline, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the sharp lyrical attack of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the hip-hop beat, making the performance feel disconnected from the track.",
      "{Name} misses every bar and ad-lib, so the number loses the flavor that this genre needs.",
      "{Name} underplays the rap hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts hard-hitting hip-hop movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the verse punchline, so the performance stays flat.",
      "{Name} seems unsure of the song’s sharp lyrical attack, giving choices that feel generic.",
      "{Name} starts with promise, but the commanding streetwise energy fades before the song really takes off.",
      "{Name} falls behind the hip-hop beat, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the rap hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the verse punchline, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "rock": {
    "good": [
      "{Name} locks into the rock drive immediately and sells the song with rebellious rock-star attitude.",
      "{Name} catches every guitar hit and snarl, making the performance feel polished and fully lived-in.",
      "{Name} turns the guitar-charged hook into a clear highlight and keeps the judges watching.",
      "{Name} uses gritty rock movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the guitar-break moment.",
      "{Name} understands the song’s amped-up grit and makes every expression feel intentional.",
      "{Name} commands the stage with raw rock intensity, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the rock drive with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the guitar-charged hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the guitar-break moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the amped-up grit of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the rock drive, making the performance feel disconnected from the track.",
      "{Name} misses every guitar hit and snarl, so the number loses the flavor that this genre needs.",
      "{Name} underplays the guitar-charged hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts gritty rock movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the guitar-break moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s amped-up grit, giving choices that feel generic.",
      "{Name} starts with promise, but the raw rock intensity fades before the song really takes off.",
      "{Name} falls behind the rock drive, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the guitar-charged hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the guitar-break moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "ballad": {
    "good": [
      "{Name} locks into the slow dramatic build immediately and sells the song with vulnerable emotional command.",
      "{Name} catches every lyric and breath, making the performance feel polished and fully lived-in.",
      "{Name} turns the emotional chorus into a clear highlight and keeps the judges watching.",
      "{Name} uses controlled dramatic movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the crescendo.",
      "{Name} understands the song’s tear-stained emotion and makes every expression feel intentional.",
      "{Name} commands the stage with quiet dramatic power, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the slow dramatic build with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the emotional chorus with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the crescendo, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the tear-stained emotion of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the slow dramatic build, making the performance feel disconnected from the track.",
      "{Name} misses every lyric and breath, so the number loses the flavor that this genre needs.",
      "{Name} underplays the emotional chorus, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts controlled dramatic movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the crescendo, so the performance stays flat.",
      "{Name} seems unsure of the song’s tear-stained emotion, giving choices that feel generic.",
      "{Name} starts with promise, but the quiet dramatic power fades before the song really takes off.",
      "{Name} falls behind the slow dramatic build, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the emotional chorus, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the crescendo, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "camp": {
    "good": [
      "{Name} locks into the campy rhythm immediately and sells the song with fearless clownish confidence.",
      "{Name} catches every joke and lyric gag, making the performance feel polished and fully lived-in.",
      "{Name} turns the silly hook into a clear highlight and keeps the judges watching.",
      "{Name} uses deliberately exaggerated movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the punchline moment.",
      "{Name} understands the song’s draggy absurdity and makes every expression feel intentional.",
      "{Name} commands the stage with chaotic comic energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the campy rhythm with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the silly hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the punchline moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the draggy absurdity of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the campy rhythm, making the performance feel disconnected from the track.",
      "{Name} misses every joke and lyric gag, so the number loses the flavor that this genre needs.",
      "{Name} underplays the silly hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts deliberately exaggerated movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the punchline moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s draggy absurdity, giving choices that feel generic.",
      "{Name} starts with promise, but the chaotic comic energy fades before the song really takes off.",
      "{Name} falls behind the campy rhythm, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the silly hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the punchline moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "theatre": {
    "good": [
      "{Name} locks into the theatrical rhythm immediately and sells the song with full Broadway commitment.",
      "{Name} catches every story beat, making the performance feel polished and fully lived-in.",
      "{Name} turns the showstopping refrain into a clear highlight and keeps the judges watching.",
      "{Name} uses character-driven stage movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the eleven-o’clock number moment.",
      "{Name} understands the song’s musical-theatre flair and makes every expression feel intentional.",
      "{Name} commands the stage with stage-ready dramatic energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the theatrical rhythm with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the showstopping refrain with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the eleven-o’clock number moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the musical-theatre flair of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the theatrical rhythm, making the performance feel disconnected from the track.",
      "{Name} misses every story beat, so the number loses the flavor that this genre needs.",
      "{Name} underplays the showstopping refrain, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts character-driven stage movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the eleven-o’clock number moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s musical-theatre flair, giving choices that feel generic.",
      "{Name} starts with promise, but the stage-ready dramatic energy fades before the song really takes off.",
      "{Name} falls behind the theatrical rhythm, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the showstopping refrain, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the eleven-o’clock number moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "country": {
    "good": [
      "{Name} locks into the country rhythm immediately and sells the song with honky-tonk confidence.",
      "{Name} catches every twangy lyric, making the performance feel polished and fully lived-in.",
      "{Name} turns the twangy chorus into a clear highlight and keeps the judges watching.",
      "{Name} uses storytelling country movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the country chorus lift.",
      "{Name} understands the song’s boot-stomping charm and makes every expression feel intentional.",
      "{Name} commands the stage with down-home performance energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the country rhythm with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the twangy chorus with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the country chorus lift, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the boot-stomping charm of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the country rhythm, making the performance feel disconnected from the track.",
      "{Name} misses every twangy lyric, so the number loses the flavor that this genre needs.",
      "{Name} underplays the twangy chorus, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts storytelling country movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the country chorus lift, so the performance stays flat.",
      "{Name} seems unsure of the song’s boot-stomping charm, giving choices that feel generic.",
      "{Name} starts with promise, but the down-home performance energy fades before the song really takes off.",
      "{Name} falls behind the country rhythm, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the twangy chorus, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the country chorus lift, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "Latin": {
    "good": [
      "{Name} locks into the Latin rhythm immediately and sells the song with fiery stage confidence.",
      "{Name} catches every percussion accent, making the performance feel polished and fully lived-in.",
      "{Name} turns the tropical hook into a clear highlight and keeps the judges watching.",
      "{Name} uses hip-driven Latin movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the rhythm-break moment.",
      "{Name} understands the song’s spicy rhythmic flair and makes every expression feel intentional.",
      "{Name} commands the stage with heated Latin dance energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the Latin rhythm with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the tropical hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the rhythm-break moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the spicy rhythmic flair of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the Latin rhythm, making the performance feel disconnected from the track.",
      "{Name} misses every percussion accent, so the number loses the flavor that this genre needs.",
      "{Name} underplays the tropical hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts hip-driven Latin movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the rhythm-break moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s spicy rhythmic flair, giving choices that feel generic.",
      "{Name} starts with promise, but the heated Latin dance energy fades before the song really takes off.",
      "{Name} falls behind the Latin rhythm, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the tropical hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the rhythm-break moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "K-pop": {
    "good": [
      "{Name} locks into the K-pop beat immediately and sells the song with camera-ready idol confidence.",
      "{Name} catches every formation-style accent, making the performance feel polished and fully lived-in.",
      "{Name} turns the idol-pop hook into a clear highlight and keeps the judges watching.",
      "{Name} uses precise K-pop choreography without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the point-choreo moment.",
      "{Name} understands the song’s glossy performance precision and makes every expression feel intentional.",
      "{Name} commands the stage with polished idol energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the K-pop beat with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the idol-pop hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the point-choreo moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the glossy performance precision of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the K-pop beat, making the performance feel disconnected from the track.",
      "{Name} misses every formation-style accent, so the number loses the flavor that this genre needs.",
      "{Name} underplays the idol-pop hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts precise K-pop choreography, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the point-choreo moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s glossy performance precision, giving choices that feel generic.",
      "{Name} starts with promise, but the polished idol energy fades before the song really takes off.",
      "{Name} falls behind the K-pop beat, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the idol-pop hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the point-choreo moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "alternative": {
    "good": [
      "{Name} locks into the alternative pulse immediately and sells the song with cool indie detachment.",
      "{Name} catches every strange little lyric, making the performance feel polished and fully lived-in.",
      "{Name} turns the offbeat hook into a clear highlight and keeps the judges watching.",
      "{Name} uses moody alternative movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the weird atmospheric turn.",
      "{Name} understands the song’s moody alt-pop edge and makes every expression feel intentional.",
      "{Name} commands the stage with left-field emotional energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the alternative pulse with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the offbeat hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the weird atmospheric turn, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the moody alt-pop edge of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the alternative pulse, making the performance feel disconnected from the track.",
      "{Name} misses every strange little lyric, so the number loses the flavor that this genre needs.",
      "{Name} underplays the offbeat hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts moody alternative movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the weird atmospheric turn, so the performance stays flat.",
      "{Name} seems unsure of the song’s moody alt-pop edge, giving choices that feel generic.",
      "{Name} starts with promise, but the left-field emotional energy fades before the song really takes off.",
      "{Name} falls behind the alternative pulse, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the offbeat hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the weird atmospheric turn, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "hyperpop": {
    "good": [
      "{Name} locks into the glitchy beat immediately and sells the song with chaotic cyber-pop confidence.",
      "{Name} catches every glitch and vocal chop, making the performance feel polished and fully lived-in.",
      "{Name} turns the maximalist hook into a clear highlight and keeps the judges watching.",
      "{Name} uses frantic hyperpop movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the glitch-drop moment.",
      "{Name} understands the song’s plastic electronic chaos and makes every expression feel intentional.",
      "{Name} commands the stage with sugar-rush hyperpop energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the glitchy beat with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the maximalist hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the glitch-drop moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the plastic electronic chaos of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the glitchy beat, making the performance feel disconnected from the track.",
      "{Name} misses every glitch and vocal chop, so the number loses the flavor that this genre needs.",
      "{Name} underplays the maximalist hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts frantic hyperpop movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the glitch-drop moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s plastic electronic chaos, giving choices that feel generic.",
      "{Name} starts with promise, but the sugar-rush hyperpop energy fades before the song really takes off.",
      "{Name} falls behind the glitchy beat, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the maximalist hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the glitch-drop moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "new wave": {
    "good": [
      "{Name} locks into the new wave pulse immediately and sells the song with cool retro confidence.",
      "{Name} catches every synth stab and lyric, making the performance feel polished and fully lived-in.",
      "{Name} turns the synthy hook into a clear highlight and keeps the judges watching.",
      "{Name} uses angular new wave movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the synth-break moment.",
      "{Name} understands the song’s stylized 80s cool and makes every expression feel intentional.",
      "{Name} commands the stage with quirky retro-club energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the new wave pulse with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the synthy hook with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the synth-break moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the stylized 80s cool of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the new wave pulse, making the performance feel disconnected from the track.",
      "{Name} misses every synth stab and lyric, so the number loses the flavor that this genre needs.",
      "{Name} underplays the synthy hook, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts angular new wave movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the synth-break moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s stylized 80s cool, giving choices that feel generic.",
      "{Name} starts with promise, but the quirky retro-club energy fades before the song really takes off.",
      "{Name} falls behind the new wave pulse, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the synthy hook, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the synth-break moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  },
  "diva": {
    "good": [
      "{Name} locks into the diva anthem build immediately and sells the song with untouchable diva authority.",
      "{Name} catches every vocal peak and lyric, making the performance feel polished and fully lived-in.",
      "{Name} turns the powerhouse chorus into a clear highlight and keeps the judges watching.",
      "{Name} uses commanding diva movement without overdoing it, matching the track with control and taste.",
      "{Name} builds the number beautifully, saving a strong reveal of energy for the money-note moment.",
      "{Name} understands the song’s full superstar drama and makes every expression feel intentional.",
      "{Name} commands the stage with grand diva energy, never letting the performance dip.",
      "{Name} gives clean musicality, hitting the diva anthem build with confidence and precision.",
      "{Name} balances face, body, and lyrics, creating a complete lip sync performance.",
      "{Name} finds the personality inside the track and makes the whole number feel specific.",
      "{Name} rides the powerhouse chorus with confidence and turns a simple phrase into a memorable moment.",
      "{Name} makes the performance feel effortless, as if the song was chosen just for them.",
      "{Name} brings strong timing to the money-note moment, landing the payoff exactly when it counts.",
      "{Name} gives enough movement to fill the stage while keeping the lip sync clear and focused.",
      "{Name} sells the attitude of the track from the first beat to the final pose.",
      "{Name} makes smart choices, highlighting the song’s biggest moments instead of fighting them.",
      "{Name} connects with the lyrics and gives the performance a clear emotional point of view.",
      "{Name} uses the stage well, turning the full superstar drama of the track into a full visual story.",
      "{Name} feels completely present in the number, reacting naturally to every shift in the music.",
      "{Name} finishes strong, leaving the performance feeling confident, clean, and fully realized."
    ],
    "bad": [
      "{Name} never quite catches the diva anthem build, making the performance feel disconnected from the track.",
      "{Name} misses every vocal peak and lyric, so the number loses the flavor that this genre needs.",
      "{Name} underplays the powerhouse chorus, letting one of the song’s biggest moments pass by unnoticed.",
      "{Name} attempts commanding diva movement, but it looks hesitant and does not match the power of the music.",
      "{Name} struggles to build toward the money-note moment, so the performance stays flat.",
      "{Name} seems unsure of the song’s full superstar drama, giving choices that feel generic.",
      "{Name} starts with promise, but the grand diva energy fades before the song really takes off.",
      "{Name} falls behind the diva anthem build, making the lip sync feel messy and unfocused.",
      "{Name} focuses so much on movement that the mouth loses accuracy and intention.",
      "{Name} gives a performance that feels safe, missing the personality inside the track.",
      "{Name} does not commit to the powerhouse chorus, which makes the number feel smaller than it should.",
      "{Name} looks like they are following the song instead of leading it.",
      "{Name} misses the timing of the money-note moment, weakening what should have been the payoff.",
      "{Name} fills the stage with movement, but very little of it feels connected to the lyrics.",
      "{Name} does not capture the attitude of the track, leaving the performance emotionally blank.",
      "{Name} makes choices that fight the song instead of supporting its strongest moments.",
      "{Name} loses the story of the lyrics, so the performance feels more technical than alive.",
      "{Name} stays stuck in one performance mode and never explores the track’s shifts.",
      "{Name} looks distracted during key musical changes, breaking the illusion of the lip sync.",
      "{Name} ends without a strong final impression, making the performance easy to forget."
    ]
  }
};
