window.MINI_CHALLENGES = [
  { id:"mini_reading_is_fundamental", description:"Reading is Fundamental", winners: 1 },
  { id:"mini_act_out_certain_emotions_and_take_pictures_of", description:"Act out certain emotions and take pictures of themselves with a digital camera.", winners: 0 },
  { id:"mini_exercise_and_endurance_challenge", description:"Exercise and endurance challenge", winners: 0 },
  { id:"mini_voguing_dance_off", description:"\"Voguing\" dance-off", winners: 0 },
  { id:"mini_turn_mini_ru_doll_from_a_lady_to_a_tramp_in_t", description:"Turn \"Mini-Ru\" doll from a lady to a tramp in teams of two", winners: 0 },
  { id:"mini_chicken_or_what_eating_contest", description:"\"Chicken or What?\" eating contest", winners: 0 },
  { id:"mini_the_queen_is_right_bidding_challenge", description:"\"The Queen is Right\" bidding challenge", winners: 0 },
  { id:"mini_give_a_wig_a_glam_rock_makeover", description:"Give a wig a glam rock makeover", winners: 0 },
  { id:"mini_quickly_match_the_seasons_contestants_with_the", description:"Quickly match the season's contestants with their baby pictures", winners: 1 },
  { id:"mini_style_and_accessorize_one_of_four_identical_dres", description:"Style and accessorize one of four identical dresses", winners: 0 },
  { id:"mini_making_leotards_from_duct_tapes", description:"Making Leotards from Duct Tapes", winners: 0 },
  { id:"mini_scandalous_red_carpet_photo", description:"Scandalous Red Carpet Photo", winners: 0 },
  { id:"mini_st_rupaul_says", description:"S**t RuPaul Says", winners: 1 },
  { id:"mini_ru_sical_chairs", description:"\"Ru\"sical Chairs", winners: 1 },
  { id:"mini_create_a_beach_themed_headpiece", description:"Create a beach-themed headpiece", winners: 1 },
  { id:"mini_dunk_a_queen", description:"Dunk-A-Queen", winners: 1 },
  { id:"mini_create_a_marketable_drag_product_and_deliver_a_s", description:"Create a marketable drag product and deliver a sales pitch for it on fictitious home shopping network \"RuVC\"", winners: 0 },
  { id:"mini_photoshoot_while_posing_on_a_spinning_platform_w", description:"Photoshoot while posing on a spinning platform while being sprayed with \"hazardous waste\".", winners: 0 },
  { id:"mini_create_a_badonkadonk_with_padding_in_30_minutes", description:"Create a \"Badonkadonk\" with padding in 30 minutes.", winners: 0 },
  { id:"mini_paint_each_others_face_while_handcuffed_to_one_a", description:"Paint each other's face while handcuffed to one another and pose for a mug shot photoshoot.", winners: 2 },
  { id:"mini_compete_in_a_game_called_beat_the_cock", description:"Compete in a game called \"Beat the Cock\"", winners: 3 },
  { id:"mini_gain_the_biggest_crowd_reaction_in_a_wet_t_shirt", description:"Gain the biggest crowd reaction in a wet T-shirt contest.", winners: 1 },
  { id:"mini_polygraph_test_administered_by_rupaul", description:"Polygraph test administered by RuPaul", winners: 0 },
  { id:"mini_design_an_absolut_vodka_inspired_shoe", description:"Design an Absolut Vodka-inspired shoe.", winners: 0 },
  { id:"mini_give_a_teddy_bear_a_makeover", description:"Give a teddy bear a makeover", winners: 0 },
  { id:"mini_everybody_loves_puppets", description:"Everybody Loves Puppets", winners: 1 },
  { id:"mini_underwater_photoshoot", description:"Underwater photoshoot", winners: 1 },
  { id:"mini_lip_sync_to_one_of_rupauls_songs_with_only_your_m", description:"Lip sync to one of RuPaul's songs with only your mouth visible.", winners: 0 },
  { id:"mini_create_a_mannequin_doll_in_pairs_for_americas_jun", description:"Create a mannequin doll in pairs for \"America's Junior Drag Superstar\" pageant", winners: 2 },
  { id:"mini_soul_train_dance_off", description:"Soul Train dance-off", winners: 0 },
  { id:"mini_style_a_cuddler_into_a_red_carpet_ready_look_for_", description:"Style a cuddler into a red carpet ready look for a Us Weekly fashion face-off", winners: 1 },
  { id:"mini_apply_drag_makeup_in_the_dark", description:"Apply drag makeup in the dark", winners: 0 },
  { id:"mini_whatcha_packin_match_male_models_wearing_the_same", description:"Whatcha Packin' - Match male models wearing the same pairs of Andrew Christian underwear", winners: 1 },
  { id:"mini_creating_fake_sob_stories_and_producing_real_tears", description:"Creating fake 'sob stories' and producing real tears in front of RuPaul", winners: 0 },
  { id:"mini_last_as_long_as_possible_in_drag_booty_camp_with_a", description:"Last as long as possible in drag booty camp with a fitness trainer", winners: 0 },
  { id:"mini_jumping_off_a_platform_photoshoot", description:"Jumping off a platform photoshoot", winners: 1 },
  { id:"mini_boudoir_pillow_fight_photoshoot_with_the_pit_crew", description:"Boudoir pillow fight photoshoot with the Pit Crew", winners: 1 },
  { id:"mini_create_a_beach_themed_lip_sync_in_pairs", description:"Create a beach themed lip sync in pairs", winners: 0 },
  { id:"mini_designing_nails_and_hand_modelling_fruits_and_veg", description:"Designing nails and hand modelling fruits and vegetables", winners: 0 },
  { id:"mini_lip_synching_to_a_rupaul_song_upside_down", description:"Lip-synching to a RuPaul song upside down", winners: 0 },
  { id:"mini_hung_men_hangman_challenge", description:"\"Hung Men\" hangman challenge", winners: 1 },
  { id:"mini_do_abstract_paintings_using_their_bodies_in_honor_o", description:"Do abstract paintings using their bodies in honor of marriage equality", winners: 0 },
  { id:"mini_keep_fish_face_as_the_pit_crew_blow_jets_of_air_in", description:"Keep fish face as the Pit Crew blow jets of air into the contestants' faces", winners: 3 },
  { id:"mini_make_their_own_paper_versions_of_classic_celebrity", description:"Make their own paper versions of classic celebrity red carpet outfits, in pairs assigned by Ru.", winners: 2 },
  { id:"mini_ask_the_members_of_the_pit_crew_to_pull_cards_out_", description:"Ask the members of the Pit Crew to pull cards out of their underwear to earn points", winners: 1 },
  { id:"mini_creating_a_look_using_prison_uniforms", description:"Creating a look using prison uniforms", winners: 0 },
  { id:"mini_create_a_fake_housewives_of_drag_race_look_using_ta", description:"Create a \"Fake Housewives of Drag Race\" look using tape.", winners: 0 },
  { id:"mini_compete_in_a_latin_dance_off_to_rupauls_song_cha_ch", description:"Compete in a latin dance-off to RuPaul's song \"Cha Cha Bitch\"", winners: 0 },
  { id:"mini_drag_up_supreme_court_robes", description:"Drag up supreme court robes", winners: 0 },
  { id:"mini_playing_a_true_or_false_guessing_game_with_the_pit_", description:"Playing a true or false guessing game with the Pit Crew", winners: 1 },
  { id:"mini_pose_in_a_sexy_selfie_with_the_pit_crew", description:"Pose in a sexy selfie with the Pit Crew", winners: 0 },
  { id:"mini_compete_in_a_country_themed_dance_competition", description:"Compete in a country-themed dance competition.", winners: 0 },
  { id:"mini_perform_in_screen_tests_for_rus_provocative_new_rup", description:"Perform in screen tests for Ru's provocative new RuPaul's Chocolate Bar campaign.", winners: 0 },
  { id:"mini_photobomb_celebrity_photographs_and_leave_a_lasting", description:"Photobomb celebrity photographs and leave a lasting impression.", winners: 0 },
  { id:"mini_transform_themselves_into_an_army_of_fierce_drag_qu", description:"Transform themselves into an army of fierce drag queens, using the contents of army duffel bags", winners: 0 },
  { id:"mini_identify_objects_only_by_sitting_on_them", description:"Identify objects only by sitting on them", winners: 0 },
  { id:"mini_slap_out_of_it", description:"Slap out of it!", winners: 0 },
  { id:"mini_pants_down_bottoms_up_remember_which_pit_crew_member", description:"Pants down, bottoms up: remember which Pit Crew members have matching underwear on", winners: 1 },
  { id:"mini_create_a_super_macho_character_and_pose_for_an_ad_fo", description:"Create a super macho character and pose for an ad for a manly body spray TRADE.", winners: 0 },
  { id:"mini_drag_up_pancakes_to_create_devastatingly_delicious_", description:"Drag up pancakes to create devastatingly delicious dishes", winners: 0 },
  { id:"mini_seduce_your_way_into_a_seduction_concert", description:"Seduce Your Way Into a Seduction Concert", winners: 0 },
  { id:"mini_channel_rachel_maddow_in_a_teleprompter_reading_chal", description:"Channel Rachel Maddow in a teleprompter reading challenge", winners: 0 },
  { id:"mini_create_and_market_a_living_doll_friend_for_rupaul_d", description:"Create and market a living doll friend for RuPaul doll.", winners: 0 },
  { id:"mini_perform_in_a_parody_calisthenics_work_out_tape_with_", description:"Perform in a parody calisthenics work out tape with Love Connie", winners: 0 },
  { id:"mini_a_potato_sack_race_serving_boob_ography", description:"A potato sack race serving boob-ography", winners: 1 },
  { id:"mini_pitch_your_own_self_help_book", description:"Pitch your own Self-Help Book", winners: 0 },
  { id:"mini_the_beehive_jive_dance_competition", description:"\"The Beehive Jive\" dance competition", winners: 0 },
  { id:"mini_pink_pill_or_silver_pill_the_two_queens_who_choose_t", description:"Pink Pill or Silver Pill: The two queens who choose the bottle with a pink pill win", winners: 2 },
  { id:"mini_curate_a_box_of_fabfitfun_products_for_another_duo_t", description:"Curate a box of FabFitFun products for another duo, then gift it to them with shade.", winners: 0 },
  { id:"mini_audition_for_the_title_of_kitty_girl_2020", description:"Audition for the title of \"Kitty Girl 2020\"", winners: 0 },
  { id:"mini_design_an_over_the_top_one_of_a_kind_showgirl_headd", description:"Design an over-the-top, one-of-a-kind showgirl headdress, that screams 'Viva Drag Vegas'.", winners: 0 },
  { id:"mini_get_into_quick_drag_and_audition_for_the_pantyhoes", description:"Get into quick drag and audition for \"The PantyHoes\"", winners: 0 },
  { id:"mini_are_you_smarter_than_the_pit_crew", description:"\"Are You Smarter Than The Pit Crew?\"", winners: 1 },
  { id:"mini_comedy_makeup_tutorials_in_pairs", description:"Comedy makeup tutorials in pairs", winners: 2 },
  { id:"mini_pose_for_a_photo_while_being_spun_around_on_the_lips", description:"Pose for a photo while being spun around on the Lipsync for the Crown wheel.", winners: 1 },
  { id:"mini_make_a_look_out_of_bubble_wrap", description:"Make a look out of bubble wrap", winners: 2 },
  { id:"mini_paint_a_mural_of_rupaul_and_dolly_parton", description:"Paint a mural of RuPaul and Dolly Parton", winners: 2 },
  { id:"mini_harlem_vogue_ball", description:"Harlem Vogue Ball", winners: 1 },
  { id:"mini_take_a_cover_photo_for_an_original_memoir_inspired_", description:"Take a cover photo for an original memoir, inspired by RuPaul's The House of Hidden Meanings", winners: 0 },
  { id:"mini_spit_take_in_response_to_comments_from_rupaul", description:"Spit Take in response to comments from RuPaul", winners: 0 },
  { id:"mini_vote_who_best_fits_the_characteristic_named_by_rupa", description:"Vote who best fits the characteristic named by RuPaul. Instead of points, the majority voters earn $100.", winners: 1 },
  { id:"mini_paint_a_custom_t_shirt_using_just_a_painted_face_in", description:"Paint a custom t-shirt using just a painted face, inspired by Tammy Faye.", winners: 0 },
  { id:"mini_climb_the_pole_and_grab_the_flag_in_the_fastest_tim", description:"Climb the pole and grab the flag in the fastest time", winners: 1 },
  { id:"mini_do_a_photoshoot_with_a_tarantula", description:"Do a photoshoot with a tarantula", winners: 1 },
  { id:"mini_play_the_lolapalooza_newspaper_dance_in_pairs", description:"Play the \"Lolapalooza Newspaper Dance\" in pairs", winners: 2 },
  { id:"mini_photoshoot_with_a_high_speed_fan_and_snow_blowing_i", description:"Photoshoot with a high speed fan and snow blowing in their faces", winners: 0 },
  { id:"mini_the_nutsmacker_a_crash_course_in_ballet", description:"The Nutsmacker: a crash course in ballet", winners: 0 },
  { id:"mini_psychic_hotline_operators", description:"Psychic Hotline Operators", winners: 0 },
  { id:"mini_queen_of_my_neighborhood_pageant", description:"Queen of My Neighborhood Pageant", winners: 0 },
  { id:"mini_get_into_artiste_quick_drag_and_paint_an_evocative_t", description:"Get into artiste quick drag and paint an evocative \"twerk of art\"", winners: 0 },
  { id:"mini_take_hockey_jerseys_and_get_into_quick_drag", description:"Take hockey jerseys and get into quick drag.", winners: 0 },
  { id:"mini_improv_your_way_through_a_tuck_talk_sponsored_by_tro", description:"Improv your way through a Tuck Talk sponsored by Trojan.", winners: 0 },
  { id:"mini_audition_for_parody_superhero_film_super_queen", description:"Audition for parody superhero film Super Queen.", winners: 0 },
  { id:"mini_metallic_photoshoot", description:"Metallic Photoshoot", winners: 0 },
  { id:"mini_get_in_quick_drag_and_get_a_fashion_consultation_by", description:"Get in quick drag and get a fashion consultation by Carson Kressley", winners: 0 },
  { id:"mini_take_part_in_a_photoshoot_challenge_depicting_the_b", description:"Take part in a photoshoot challenge depicting the beheading of Anne Boleyn.", winners: 1 },
  { id:"mini_dance_around_a_maypole", description:"Dance around a maypole", winners: 0 },
  { id:"mini_limbo_for_your_life", description:"Limbo for your Life", winners: 2 },
  { id:"mini_present_a_pastry_in_a_sexual_manner", description:"Present a pastry in a sexual manner", winners: 1 },
  { id:"mini_the_masc_4_masc_singer", description:"The Masc 4 Masc Singer", winners: 1 },
  { id:"mini_rus_dirty_charades", description:"Ru's Dirty Charades", winners: 0 },
  { id:"mini_create_a_straight_male_character_and_market_it_in_a", description:"Create a straight male character and market it in a Tinder spoof \"Findhr\"", winners: 1 },
  { id:"mini_pose_and_deliver_a_sticky_tag_line_in_dtf_bro_drag", description:"Pose and deliver a sticky tag line in DTF bro drag", winners: 1 },
  { id:"mini_try_to_make_rupaul_and_raven_laugh_while_sitting_in_", description:"Try to make RuPaul and Raven laugh while sitting in a pink furry chair", winners: 0 },
  { id:"mini_palong_palosebo_climb_the_pole_and_grab_the_flag_in_", description:"Palong-Palosebo: climb the pole and grab the flag in the fastest time", winners: 1 },
  { id:"mini_drag_race_special_ru_lection_rank_your_fellow_contes", description:"Drag Race Special Ru-lection: Rank your fellow contestants based on your impression of them", winners: 2 },
  { id:"mini_play_a_round_of_ten_twenty_talon_beki_a_chinese_garte", description:"Play a round of Ten-Twenty Talon Beki, a Chinese Garter game", winners: 1 },
  { id:"mini_nude_illusion_group_photoshoot", description:"Nude Illusion Group Photoshoot", winners: 1 },
  { id:"mini_play_the_lolapalooza_newspaper_dance_in_pairs_2", description:"Play the \"Lolapalooza Newspaper Dance\" in pairs", winners: 2 },
  { id:"mini_tinikling_for_your_life_perform_the_tinikling_for_t", description:"Tinikling for Your Life: perform the tinikling for the longest time possible", winners: 1 },
  { id:"mini_play_trip_to_jerusalem_musical_chairs", description:"Play Trip to Jerusalem/musical chairs", winners: 1 },
  { id:"mini_do_makeup_while_using_only_one_compact_mirror_and_po", description:"Do makeup while using only one compact mirror and pose for a mini-photoshoot", winners: 1 },
  { id:"mini_perform_voguing_moves_in_front_of_your_fellow_castma", description:"Perform voguing moves in front of your fellow castmates while walking the Main Stage", winners: 1 },
  { id:"mini_tins_tins_tins_across_the_board_play_a_game_of_tumba", description:"Tins, Tins, Tins Across the Board: Play a game of tumbang preso", winners: 1 },
  { id:"mini_whats_in_a_box_beks_while_blindfolded_guess_the_cont", description:"What's in a Box, Beks?: while blindfolded, guess the contents of four boxes within two minutes.", winners: 1 },
  { id:"mini_photoshoot_for_a_90s_inspired_notebook_cover", description:"Photoshoot for a 90's inspired notebook cover", winners: 1 },
  { id:"mini_while_blindfolded_attempt_to_smash_a_hanging_clay_po", description:"While blindfolded, attempt to smash a hanging clay pot within one minute.", winners: 1 },
  { id:"mini_in_groups_of_two_make_a_tutorial_on_how_to_make_a_ba", description:"In groups of two, make a tutorial on how to make a baguette", winners: 2 },
  { id:"mini_improvise_wedding_vows_and_play_wedding_games", description:"Improvise wedding vows and play wedding games", winners: 2 },
  { id:"mini_get_in_quick_drag_and_play_in_a_parody_of_the_game_s", description:"Get in quick drag and play in a parody of the game show Fort Boyard", winners: 1 },
  { id:"mini_get_in_quick_drag_and_play_in_the_jeux_olymp_queens", description:"Get in quick drag and play in the Jeux Olymp-Queens.", winners: 1 },
  { id:"mini_get_in_quick_drag_and_play_a_game_of_twister_bingo", description:"Get in quick drag and play a game of twister bingo", winners: 1 },
  { id:"mini_get_in_20_minutes_quick_drag_and_partake_in_a_photos", description:"Get in 20-minutes quick drag and partake in a photoshoot for the cover of Quick Drag Magazine", winners: 0 },
  { id:"mini_guess_the_total_population_of_countries", description:"Guess the total population of countries", winners: 1 },
  { id:"mini_do_makeup_mid_air", description:"Do makeup mid-air", winners: 0 },
  { id:"mini_guess_scrambled_words_in_draga_palabra", description:"Guess scrambled words in Draga-palabra", winners: 1 },
  { id:"mini_design_a_drag_sports_outfit_and_create_a_drag_footba", description:"Design a drag sports outfit and create a drag football player persona", winners: 0 },
  { id:"mini_grape_treading_in_pairs", description:"Grape treading in pairs", winners: 2 },
  { id:"mini_memorize_and_recite_famous_poetry_while_having_a_fan", description:"Memorize and recite famous poetry while having a fan blowing on their face and several items thrown at them", winners: 1 },
  { id:"mini_last_the_longest_in_a_sumo_fight_wearing_sumo", description:"Last the longest in a sumo-fight wearing sumo-fighting outfits.", winners: 1 },
  { id:"mini_audition_for_the_new_movie_thar", description:"Audition for the new movie: Thar", winners: 0 },
  { id:"mini_show_their_best_slow_motion_surf_rescue", description:"Show their best slow-motion surf rescue", winners: 0 }
];
