window.RUNWAYS = [
  { id:"runway_dress_to_impress", name:"Dress to Impress" },
  { id:"runway_high_class_drag", name:"High-Class Drag" },
  { id:"runway_country_realness", name:"Country Realness" },
  { id:"runway_personal_style", name:"Personal Style" },
  { id:"runway_rocker_chick", name:"Rocker Chick" },
  { id:"runway_futurama_glamorama", name:"Futurama Glamorama" },
  { id:"runway_favorite_body_part", name:"Favorite Body Part" },
  { id:"runway_extravagant_drag", name:"Extravagant Drag" },
  { id:"runway_favorite_drag_look", name:"Favorite Drag Look" },
  { id:"runway_patriotic_drag", name:"Patriotic Drag" },
  { id:"runway_girly_girl_couture", name:"Girly Girl Couture" },
  { id:"runway_platinum_gold", name:"Platinum & Gold" },
  { id:"runway_red_carpet", name:"Red Carpet" },
  { id:"runway_inaugural_ball", name:"Inaugural Ball" },
  { id:"runway_think_pink", name:"Think Pink" },
  { id:"runway_divalicious", name:"Divalicious" },
  { id:"runway_deadliest_snatch_glamour", name:"Deadliest Snatch Glamour" },
  { id:"runway_latina_eleganza", name:"Latina Eleganza" },
  { id:"runway_tony_awards_glamour", name:"Tony Awards Glamour" },
  { id:"runway_a_night_of_a_thousand_rupauls", name:"A Night of A Thousand RuPauls" },
  { id:"runway_crazy_sexy_cool", name:"Crazy Sexy Cool" },
  { id:"runway_black_white", name:"Black & White" },
  { id:"runway_animal_kingdom_couture", name:"Animal Kingdom Couture" },
  { id:"runway_jetset_eleganza", name:"Jetset Eleganza" },
  { id:"runway_bearded_and_beautiful", name:"Bearded and Beautiful" },
  { id:"runway_green", name:"Green" },
  { id:"runway_award_show", name:"Award Show" },
  { id:"runway_death_becomes_her", name:"Death Becomes Her" },
  { id:"runway_leather_and_lace", name:"Leather and Lace" },
  { id:"runway_ugliest_dress_ever", name:"Ugliest Dress Ever" },
  { id:"runway_half_man_half_woman", name:"Half Man, Half Woman" },
  { id:"runway_movie_premiere_realness", name:"Movie Premiere Realness" },
  { id:"runway_rollergirls", name:"Rollergirls" },
  { id:"runway_neon_realness", name:"Neon Realness" },
  { id:"runway_night_of_a_thousand_madonnas", name:"Night of a Thousand Madonnas" },
  { id:"runway_black_and_white_realness", name:"Black and White Realness" },
  { id:"runway_white_party_realness", name:"White Party Realness" },
  { id:"runway_naughty_nighty", name:"Naughty Nighty" },
  { id:"runway_faux_fur_realness", name:"Faux Fur Realness" },
  { id:"runway_big_hair_everywhere", name:"Big Hair Everywhere" },
  { id:"runway_club_kid_couture", name:"Club Kid Couture" },
  { id:"runway_feathers", name:"Feathers" },
  { id:"runway_denim_diamonds", name:"Denim & Diamonds" },
  { id:"runway_hats_incredible", name:"Hats Incredible" },
  { id:"runway_mermaid_fantasy", name:"Mermaid Fantasy" },
  { id:"runway_glitterific", name:"Glitterific" },
  { id:"runway_silver_foxy", name:"Silver Foxy" },
  { id:"runway_whats_your_sign", name:"What's Your Sign?" },
  { id:"runway_fringe", name:"Fringe" },
  { id:"runway_orange_alert", name:"Orange Alert" },
  { id:"runway_all_that_glitters_is_gold", name:"All That Glitters Is Gold" },
  { id:"runway_sequins_on_the_runway", name:"Sequins on the Runway" },
  { id:"runway_facekini_realness", name:"Facekini Realness" },
  { id:"runway_caftan_realness", name:"Caftan Realness" },
  { id:"runway_sparkle", name:"Sparkle" },
  { id:"runway_tulle", name:"Tulle" },
  { id:"runway_buttons_and_bows", name:"Buttons and Bows" },
  { id:"runway_planet_of_the_capes", name:"Planet of the Capes" },
  { id:"runway_frozen_eleganza", name:"Frozen Eleganza" },
  { id:"runway_night_of_a_thousand_michelle_visages", name:"Night of a Thousand Michelle Visages" },
  { id:"runway_black_wedding", name:"Black Wedding" },
  { id:"runway_stars_and_stripes_forever", name:"Stars and Stripes Forever" },
  { id:"runway_the_color_purple", name:"The Color Purple" },
  { id:"runway_lame_you_stay", name:"Lamé You Stay" },
  { id:"runway_were_here_were_sheer_get_used_to_it", name:"We're Here, We're Sheer, Get Used To It" },
  { id:"runway_trains_for_days", name:"Trains for Days" },
  { id:"runway_little_black_dress", name:"Little Black Dress" },
  { id:"runway_bead_it", name:"Bead It!" },
  { id:"runway_yellow_gorgeous", name:"Yellow, Gorgeous" },
  { id:"runway_fascinating_fascinators", name:"Fascinating Fascinators" },
  { id:"runway_beast_couture", name:"BEAST Couture" },
  { id:"runway_haute_pockets", name:"Haute Pockets" },
  { id:"runway_night_of_a_thousand_jlos", name:"Night of a Thousand JLo's" },
  { id:"runway_spring_has_sprung_look", name:"Spring Has Sprung Look" },
  { id:"runway_glamazon_primetime", name:"Glamazon Primetime" },
  { id:"runway_chaps_on_the_runway", name:"Chaps on the Runway" },
  { id:"runway_heart_on", name:"Heart On" },
  { id:"runway_shoulder_pads", name:"Shoulder Pads" },
  { id:"runway_holy_couture", name:"Holy Couture" },
  { id:"runway_mirror_mirror", name:"Mirror, Mirror" },
  { id:"runway_tutu_much", name:"Tutu Much" },
  { id:"runway_metallica", name:"Metallica" },
  { id:"runway_beautiful_nightmare", name:"Beautiful Nightmare" },
  { id:"runway_tie_dye_to_die_for", name:"Tie-Dye to Die For" },
  { id:"runway_puffer_please", name:"Puffer Please!" },
  { id:"runway_night_of_1000_beyonces", name:"Night of 1000 Beyoncés" },
  { id:"runway_rip_her_to_shreds", name:"Rip Her to Shreds!" },
  { id:"runway_everybody_say_glove", name:"Everybody Say Glove!" },
  { id:"runway_ruveal_yourself", name:"Ruveal Yourself" },
  { id:"runway_everything_every_cher_all_at_once", name:"Everything Every-Cher All at Once" },
  { id:"runway_faster_pussycat_wig_wig", name:"Faster Pussycat, Wig! Wig!" },
  { id:"runway_i_can_buy_myself_flowers", name:"I Can Buy Myself Flowers" },
  { id:"runway_dancing_queens", name:"Dancing Queens" },
  { id:"runway_true_colors", name:"True Colors" },
  { id:"runway_flashback_dragcon_1980", name:"Flashback: DragCon 1980" },
  { id:"runway_chain_reaction", name:"Chain Reaction" },
  { id:"runway_fandango", name:"Fandango" },
  { id:"runway_masked_for_masked_singer", name:"Masked for Masked Singer" },
  { id:"runway_is_it_cake", name:"Is It Cake?" },
  { id:"runway_quilted_for_your_pleasure", name:"Quilted for Your Pleasure" },
  { id:"runway_tickled_pink", name:"Tickled Pink" },
  { id:"runway_nailed_it", name:"Nailed It" },
  { id:"runway_parasols_shady_ladies", name:"Parasols, Shady Ladies" },
  { id:"runway_who_wears_short_shorts", name:"Who Wears Short Shorts?" },
  { id:"runway_black_white_ball", name:"Black & White Ball" },
  { id:"runway_ugliest_dress_ever_2", name:"Ugliest Dress Ever" },
  { id:"runway_opulent_outerwear", name:"Opulent Outerwear" },
  { id:"runway_60s_glam", name:"60's Glam" },
  { id:"runway_bad_girl_chic", name:"Bad Girl Chic" },
  { id:"runway_latex_extravaganza", name:"Latex Extravaganza" },
  { id:"runway_the_future_of_drag", name:"The Future of Drag" },
  { id:"runway_pants_on_the_runway", name:"Pants on the Runway" },
  { id:"runway_wigs_on_wigs_on_wigs", name:"Wigs on Wigs on Wigs" },
  { id:"runway_flower_power", name:"Flower Power" },
  { id:"runway_red_for_filth", name:"Red For Filth" },
  { id:"runway_icy_iridescence", name:"Icy Iridescence" },
  { id:"runway_eleguence_after_dark", name:"Eleguence After Dark" },
  { id:"runway_boots_the_house_down", name:"Boots the House Down" },
  { id:"runway_curves_and_swerves_padded_for_the_gods", name:"Curves and Swerves: Padded for the Gods" },
  { id:"runway_angelic_white", name:"Angelic White" },
  { id:"runway_plastique_fantastique", name:"Plastique Fantastique" },
  { id:"runway_kitty_cat_couture", name:"Kitty Cat Couture" },
  { id:"runway_love_the_skin_youre_in", name:"Love The Skin You're In" },
  { id:"runway_three_three_three_looks_in_one", name:"Three! Three! Three Looks In One" },
  { id:"runway_cmon_camo_couture", name:"C'mon, Camo Couture" },
  { id:"runway_prom_queen_fantasy", name:"Prom Queen Fantasy" },
  { id:"runway_freak_out", name:"Freak Out!" },
  { id:"runway_the_frill_of_it_all", name:"The Frill of it All" },
  { id:"runway_clash_of_the_patterns", name:"Clash of the Patterns" },
  { id:"runway_oh_my_goth", name:"Oh, My Goth!" },
  { id:"runway_hot_tropics", name:"Hot Tropics" },
  { id:"runway_pop_art", name:"Pop Art" },
  { id:"runway_a_fashionable_fashion_fail", name:"A Fashionable Fashion Fail" },
  { id:"runway_nude_and_crystal", name:"Nude and Crystal" },
  { id:"runway_im_crowning", name:"I'm Crowning" },
  { id:"runway_the_pleather_principle", name:"The Pleather Principle" },
  { id:"runway_spikes_on_the_runway", name:"Spikes on the Runway" },
  { id:"runway_veiled_it", name:"Veiled It" },
  { id:"runway_night_of_1000_dolly_partons", name:"Night of 1000 Dolly Partons" },
  { id:"runway_knitty_knitty_bang_bang", name:"Knitty Knitty Bang Bang" },
  { id:"runway_what_lies_beneath", name:"What Lies Beneath" },
  { id:"runway_all_glowed_up", name:"All Glowed Up" },
  { id:"runway_famous_forever", name:"Famous Forever" },
  { id:"runway_net_gala", name:"Net Gala" },
  { id:"runway_ass_the_world_turns", name:"ASS The World Turns" },
  { id:"runway_ruveal_yourself_2", name:"Ruveal Yourself" },
  { id:"runway_night_of_a_thousand_grace_joneses", name:"Night of a Thousand Grace Joneses" },
  { id:"runway_miss_fill_in_the_blank", name:"Miss Fill-in-the-Blank" },
  { id:"runway_snow_bunny", name:"Snow Bunny" },
  { id:"runway_red_white_and_blue", name:"Red, White and Blue" },
  { id:"runway_goddesses_who_save_the_world", name:"Goddesses Who Save The World" },
  { id:"runway_signature_fragrance_style", name:"Signature Fragrance Style" },
  { id:"runway_a_tail_and_two_titties", name:"A Tail and Two Titties" },
  { id:"runway_day_to_night_ruveal", name:"Day to Night Ruveal" },
  { id:"runway_atomic_blonde", name:"Atomic Blonde" },
  { id:"runway_widow_weep_for_me", name:"Widow, Weep for Me" },
  { id:"runway_bring_back_my_pearls", name:"Bring Back My Pearls" },
  { id:"runway_slits_and_tits", name:"Slits and Tits" },
  { id:"runway_coming_and_going", name:"Coming and Going" },
  { id:"runway_little_shop_of_whores", name:"Little Shop of Whores" },
  { id:"runway_wild_wild_west", name:"Wild, Wild West" },
  { id:"runway_night_of_a_thousand_mileys", name:"Night of a Thousand Miley's" },
  { id:"runway_paper_dolls", name:"Paper Dolls" },
  { id:"runway_tear_a_me_suit", name:"Tear-A-Me-Suit" },
  { id:"runway_foiled_again", name:"Foiled Again" },
  { id:"runway_power_of_love", name:"Power of Love" },
  { id:"runway_silk_extravaganza", name:"Silk Extravaganza" },
  { id:"runway_rainbow_after_the_rain", name:"Rainbow After the Rain" },
  { id:"runway_ugly_and_beautiful", name:"Ugly and Beautiful" },
  { id:"runway_hollywood_in_your_heart", name:"Hollywood in your Heart" },
  { id:"runway_miss_star_of_the_galaxy", name:"Miss Star of the Galaxy" },
  { id:"runway_white_elephant", name:"White Elephant" },
  { id:"runway_world_wild_wet", name:"World Wild WET" },
  { id:"runway_i_dont_need_a_sugar_daddy_i_am_a_sugar_daddy", name:"I Don't Need a Sugar Daddy, I AM a Sugar Daddy!" },
  { id:"runway_clown_is_sexy_and_i_know_it", name:"Clown is Sexy and I Know It" },
  { id:"runway_love_is_blind", name:"Love is Blind" },
  { id:"runway_the_iconic", name:"The Iconic" },
  { id:"runway_hairrrhh", name:"HAIRRRHHH!" },
  { id:"runway_bond_girl_glamourama", name:"Bond Girl Glamourama" },
  { id:"runway_weird_science_genetically_modified_drag_queens", name:"Weird Science: Genetically Modified Drag Queens" },
  { id:"runway_a_day_at_the_races", name:"A Day at the Races" },
  { id:"runway_rainy_day_eleganza", name:"Rainy Day Eleganza" },
  { id:"runway_surprise_surprise", name:"Surprise, Surprise" },
  { id:"runway_monster_mashup", name:"Monster Mashup" },
  { id:"runway_a_day_at_the_seaside", name:"A Day at the Seaside" },
  { id:"runway_preherstoric", name:"PreHERstoric" },
  { id:"runway_stoned_on_the_runway", name:"Stoned On The Runway" },
  { id:"runway_panto_dames", name:"Panto Dames" },
  { id:"runway_red_carpet_showstoppers", name:"Red Carpet Showstoppers" },
  { id:"runway_night_of_a_thousand_spice_girls", name:"Night of a Thousand Spice Girls" },
  { id:"runway_expenny_henny", name:"Expenny, Henny" },
  { id:"runway_feeling_fruity", name:"Feeling Fruity" },
  { id:"runway_scene_stealers", name:"Scene Stealers" },
  { id:"runway_oh_my_goddess", name:"Oh My Goddess" },
  { id:"runway_neon_nights", name:"Neon Nights" },
  { id:"runway_the_mane_event", name:"The Mane Event" },
  { id:"runway_west_end_wonders", name:"West End Wonders" },
  { id:"runway_tickled_pink_2", name:"Tickled Pink" },
  { id:"runway_ruff_and_ready", name:"Ruff and Ready" },
  { id:"runway_pretty_in_punk", name:"Pretty in Punk" },
  { id:"runway_night_of_a_thousand_pop_icons", name:"Night of A Thousand Pop Icons" },
  { id:"runway_slaycation", name:"Slaycation" },
  { id:"runway_pajamarama", name:"Pajamarama" },
  { id:"runway_poofs_on_parade", name:"Poofs on Parade" },
  { id:"runway_new_romantics", name:"New Romantics" },
  { id:"runway_call_me_mother_nature", name:"Call Me Mother Nature" },
  { id:"runway_hows_your_head_piece", name:"How's Your Head...Piece?" },
  { id:"runway_doctor_who_is_she", name:"Doctor Who Is She?" },
  { id:"runway_night_of_a_1000_princess_dianas", name:"Night of A 1000 Princess Dianas" },
  { id:"runway_vinyl", name:"Vinyl" },
  { id:"runway_cuddly_wuddly", name:"Cuddly Wuddly" },
  { id:"runway_ab_fab_night_of_1000_sweetie_darlings", name:"Ab Fab!: Night of 1000 Sweetie Darlings" },
  { id:"runway_having_it_large", name:"Having It Large" },
  { id:"runway_battle_axe_warrior_queens", name:"Battle Axe - Warrior Queens" },
  { id:"runway_holiday_ho_ho_hos", name:"Holiday Ho Ho Hos" },
  { id:"runway_english_country_garden", name:"English Country Garden" },
  { id:"runway_epic_eleganza", name:"Epic Eleganza" },
  { id:"runway_not_my_first_time", name:"Not My First Time" },
  { id:"runway_becky_with_the_good_hair", name:"Becky With The Good Hair" },
  { id:"runway_night_of_a_thousand_celine_dion", name:"Night of a Thousand Céline Dion" },
  { id:"runway_denim_on_denim_on_denim", name:"Denim on Denim on Denim" },
  { id:"runway_pageant_perfection", name:"Pageant Perfection" },
  { id:"runway_circus_bezerkus", name:"Circus Bezerkus" },
  { id:"runway_good_girl_gone_bad", name:"Good Girl Gone Bad" },
  { id:"runway_monochromatica_futuristic_pop_princess", name:"Monochromatica: Futuristic Pop Princess" },
  { id:"runway_dungeons_and_drag_queens", name:"Dungeons and Drag Queens" },
  { id:"runway_pastel_perfection", name:"Pastel Perfection" },
  { id:"runway_goddesses_of_the_ancient_world", name:"Goddesses of the Ancient World" },
  { id:"runway_sleeves", name:"Sleeves" },
  { id:"runway_periodic_table_of_elements", name:"Periodic Table of Elements" },
  { id:"runway_paint", name:"Paint" },
  { id:"runway_dystopian_drag", name:"Dystopian Drag" },
  { id:"runway_goddesses_of_the_sun", name:"Goddesses of the Sun" },
  { id:"runway_gemstones", name:"Gemstones" },
  { id:"runway_sunglasses_at_night", name:"Sunglasses at Night" },
  { id:"runway_steampunk", name:"Steampunk" },
  { id:"runway_always_a_bridesmaid", name:"Always a Bridesmaid" },
  { id:"runway_queen_bee", name:"Queen Bee" },
  { id:"runway_time_and_place", name:"Time and Place" },
  { id:"runway_grunge_and_glamour", name:"Grunge and Glamour" },
  { id:"runway_alien_superstar", name:"Alien Superstar" },
  { id:"runway_statuesque", name:"Statuesque" },
  { id:"runway_more_is_more", name:"More is More" },
  { id:"runway_in_the_shadows", name:"In the Shadows" },
  { id:"runway_my_chemical_reaction", name:"My Chemical Reaction" },
  { id:"runway_give_face_face_face", name:"Give Face, Face, Face" },
  { id:"runway_shine_bright_like_a_diamond", name:"Shine Bright Like a Diamond" },
  { id:"runway_nightlife_extravaganza", name:"Nightlife Extravaganza" },
  { id:"runway_statements_on_the_runway", name:"Statements on the Runway" },
  { id:"runway_back_to_my_roots", name:"Back To My Roots" },
  { id:"runway_opposites_attract", name:"Opposites Attract" },
  { id:"runway_sea_sickening", name:"Sea Sickening" },
  { id:"runway_fly_girls_insects_on_the_runway", name:"Fly Girls: Insects on the Runway" },
  { id:"runway_cirque_du_so_gay", name:"Cirque Du So-Gay" },
  { id:"runway_belts_buckles_chains", name:"Belts, Buckles & Chains" },
  { id:"runway_swimsuit_edition", name:"Swimsuit Edition" },
  { id:"runway_swimsuit_edition_2", name:"Swimsuit Edition" },
  { id:"runway_bad_girl_gone_bad_2", name:"Bad Girl Gone Bad" },
  { id:"runway_queen_of_dessert", name:"Queen of Dessert" },
  { id:"runway_liquid_dreams", name:"Liquid Dreams" },
  { id:"runway_tribute_to_la_veneno", name:"Tribute To La Veneno" },
  { id:"runway_marbella_jet_set", name:"Marbella Jet-Set" },
  { id:"runway_the_day_of_the_beast", name:"The Day of The Beast" },
  { id:"runway_dot_dot_dot", name:"Dot Dot Dot" },
  { id:"runway_luck_be_a_lady", name:"Luck Be A Lady" },
  { id:"runway_werk_of_art", name:"Werk of Art" },
  { id:"runway_gone_cruising", name:"Gone Cruising" },
  { id:"runway_business_in_the_front_party_in_the_back", name:"Business in the Front, Party in the Back" },
  { id:"runway_liberty_equality_jean_paul_gaultier", name:"Liberty, Equality, Jean Paul Gaultier" },
  { id:"runway_the_day_after_a_night_out", name:"The Day After a Night Out" },
  { id:"runway_led_there_be_light", name:"LED There Be Light" },
  { id:"runway_the_shoooos", name:"The Shoooes!" },
  { id:"runway_can_i_get_an_alien", name:"Can I Get an Alien?" },
  { id:"runway_wild_life_couture_extravaganza", name:"Wild Life Couture Extravaganza" },
  { id:"runway_3d_fractal_extravaganza", name:"3D Fractal Extravaganza" },
  { id:"runway_gosh_with_the_wind", name:"Gosh With the Wind" },
  { id:"runway_celestial_bodies", name:"Celestial Bodies" },
  { id:"runway_plaid_girls_club", name:"Plaid Girls Club" },
  { id:"runway_y2gay_2000s_club_kids", name:"Y2GAY: 2000s Club Kids" },
  { id:"runway_wonders_of_the_world", name:"Wonders of the World" },
  { id:"runway_mother_nature", name:"Mother Nature" },
  { id:"runway_razzle_dazzle", name:"Razzle Dazzle" },
  { id:"runway_summer_of_69", name:"Summer of '69" },
  { id:"runway_silver_girls", name:"Silver Girls" },
  { id:"runway_folk_futurism", name:"Folk-Futurism" },
  { id:"runway_rave_parade", name:"Rave Parade" },
  { id:"runway_dinner_is_served", name:"Dinner is Served" },
  { id:"runway_a_hairy_affair", name:"A Hairy Affair" },
  { id:"runway_opera_queens", name:"Opera Queens" },
  { id:"runway_garden_of_eden", name:"Garden of Eden" },
  { id:"runway_money_makes_the_world_go_round", name:"Money Makes the World Go Round" },
  { id:"runway_color_my_world", name:"Color My World" },
  { id:"runway_browntown", name:"Browntown" },
  { id:"runway_star_trek_queens_in_outer_space", name:"Star Trek: Queens in Outer Space" },
  { id:"runway_star_warrior", name:"Star Warrior" },
  { id:"runway_extra_large_wings", name:"Extra Large Wings" },
  { id:"runway_i_didnt_get_anything_done", name:"I Didn't Get Anything Done!" },
  { id:"runway_tech_couture", name:"Tech Couture" },
  { id:"runway_happy_face_tival", name:"Happy Face-tival" },
  { id:"runway_mythical_creature_couture", name:"Mythical Creature Couture" },
  { id:"runway_defying_gravity", name:"Defying Gravity" }
];
