window.SNATCH_GAME_CHARACTERS = [
  { id: "001", name: "Britney Spears" },
  { id: "002", name: "Carol Channing" },
  { id: "003", name: "RuPaul" },
  { id: "004", name: "Paris Hilton" },
  { id: "005", name: "Whitney Houston" },
  { id: "006", name: "Beyoncé" },
  { id: "007", name: "Kimora Lee" },
  { id: "008", name: "P!nk" },
  { id: "009", name: "Lady Gaga" },
  { id: "010", name: "Mo'Nique" },
  { id: "011", name: "Alicia Keys" },
  { id: "012", name: "Tyra Banks" },
  { id: "013", name: "Jennifer Lopez" },
  { id: "014", name: "Tina Turner" },
  { id: "015", name: "Cher" },
  { id: "016", name: "Joan Crawford" },
  { id: "017", name: "Michelle Visage" },
  { id: "018", name: "Jessica Simpson" },
  { id: "019", name: "Wendy Williams" },
  { id: "020", name: "Snooki" },
  { id: "021", name: "Little Edie" },
  { id: "022", name: "Lady Bunny" },
  { id: "023", name: "Tamar Braxton" },
  { id: "024", name: "Taylor Swift" },
  { id: "025", name: "Katy Perry" },
  { id: "026", name: "Marilyn Monroe" },
  { id: "027", name: "Ke$ha" },
  { id: "028", name: "Maggie Smith" },
  { id: "029", name: "Anna Nicole Smith" },
  { id: "030", name: "Judge Judy" },
  { id: "031", name: "Fran Drescher" },
  { id: "032", name: "Paula Deen" },
  { id: "033", name: "Teresa Giudice" },
  { id: "034", name: "Julia Child" },
  { id: "035", name: "Rachel Zoe" },
  { id: "036", name: "Kim Kardashian" },
  { id: "037", name: "Adele" },
  { id: "038", name: "Little Richard" },
  { id: "039", name: "Suze Orman" },
  { id: "040", name: "Big Ang" },
  { id: "041", name: "Donatella Versace" },
  { id: "042", name: "Raven-Symoné" },
  { id: "043", name: "Uzo Aduba" },
  { id: "044", name: "Michael Jackson" },
  { id: "045", name: "Eartha Kitt" },
  { id: "046", name: "Diana Vreeland" },
  { id: "047", name: "Tiffany New York Pollard" },
  { id: "048", name: "Nancy Grace" },
  { id: "049", name: "Liza Minnelli" },
  { id: "050", name: "Marlene Dietrich" },
  { id: "051", name: "Naomi Campbell" },
  { id: "052", name: "Amanda Lepore" },
  { id: "053", name: "Gigi Gorgeous" },
  { id: "054", name: "NeNe Leakes" },
  { id: "055", name: "Sofía Vergara" },
  { id: "056", name: "Melania Trump" },
  { id: "057", name: "Honey Boo Boo" },
  { id: "058", name: "Maya Angelou" },
  { id: "059", name: "Chyna" },
  { id: "060", name: "Dorothy Parker" },
  { id: "061", name: "Blue Ivy Carter" },
  { id: "062", name: "Ts Madison" },
  { id: "063", name: "Harvey Fierstein" },
  { id: "064", name: "Charo" },
  { id: "065", name: "Tiffany Haddish" },
  { id: "066", name: "Danielle Bregoli" },
  { id: "067", name: "Céline Dion" },
  { id: "068", name: "Whoopi Goldberg" },
  { id: "069", name: "Sophia The Robot" },
  { id: "070", name: "Lisa Rinna" },
  { id: "071", name: "Katharine Hepburn" },
  { id: "072", name: "Leslie Jones" },
  { id: "073", name: "Bernadette Peters" },
  { id: "074", name: "Patricia Quinn" },
  { id: "075", name: "Jonathan Van Ness" },
  { id: "076", name: "Mary, Queen Of Scots" },
  { id: "077", name: "Patrick Starrr" },
  { id: "078", name: "Richard Simmons" },
  { id: "079", name: "Bob Ross" },
  { id: "080", name: "Rue McClanahan" },
  { id: "081", name: "Lil Jon" },
  { id: "082", name: "Ozzy Osbourne" },
  { id: "083", name: "Drew Barrymore" },
  { id: "084", name: "Ilana Glazer" },
  { id: "085", name: "Tammie Brown" },
  { id: "086", name: "William Shakespeare" },
  { id: "087", name: "Gwyneth Paltrow" },
  { id: "088", name: "Betsy DeVos" },
  { id: "089", name: "Tim Gunn" },
  { id: "090", name: "Joan Rivers" },
  { id: "091", name: "Rosie O'Donnell" },
  { id: "092", name: "Tan Mom" },
  { id: "093", name: "Gordon Ramsay" },
  { id: "094", name: "Mona Lisa" },
  { id: "095", name: "Jan Crouch" },
  { id: "096", name: "Saucy Santana" },
  { id: "097", name: "Bretman Rock" },
  { id: "098", name: "Miley Cyrus" },
  { id: "099", name: "Virgin Mary" },
  { id: "100", name: "Trisha Paytas" },
  { id: "101", name: "Jelena Karleuša" },
  { id: "102", name: "James Brown" },
  { id: "103", name: "Meghan McCain" },
  { id: "104", name: "Patti LuPone" },
  { id: "105", name: "Amelia Earhart" },
  { id: "106", name: "Jane Goodall" },
  { id: "107", name: "The Tooth Fairy" },
  { id: "108", name: "Eddie Murphy" },
  { id: "109", name: "Bigfoot" },
  { id: "110", name: "Gilbert Gottfried" },
  { id: "111", name: "Kim Gravel" },
  { id: "112", name: "David Lynch" },
  { id: "113", name: "Ellen Greene" },
  { id: "114", name: "Cupid" },
  { id: "115", name: "Nicole Richie" },
  { id: "116", name: "Courtney Love" },
  { id: "117", name: "Betsy Johnson" },
  { id: "118", name: "Rebel Wilson" },
  { id: "119", name: "Taraji P. Henson As Cookie Lyon" },
  { id: "120", name: "Christina Aguilera" },
  { id: "121", name: "Lois Griffin" },
  { id: "122", name: "Santa Claus" },
  { id: "123", name: "Lucille Ball" },
  { id: "124", name: "Lana Del Rey" },
  { id: "125", name: "Shelley Duvall" },
  { id: "126", name: "Marie Antoinette" },
  { id: "127", name: "Aubrey Plaza" },
  { id: "128", name: "Jamie Lee Curtis" },
  { id: "129", name: "Leslie Jordan" },
  { id: "130", name: "Kim Zolciak-Biermann" },
  { id: "131", name: "Joy Behar" },
  { id: "132", name: "Mariah Carey" },
  { id: "133", name: "Julia Fox" },
  { id: "134", name: "Sarah Paulson" },
  { id: "135", name: "Martha Stewart" },
  { id: "136", name: "Bernie Sanders" },
  { id: "137", name: "Ethel Merman" },
  { id: "138", name: "Celia Cruz" },
  { id: "139", name: "Charlie The Turkey" },
  { id: "140", name: "Betty Crocker" },
  { id: "141", name: "Shakira" },
  { id: "142", name: "Bette Davis" },
  { id: "143", name: "Bea Arthur" },
  { id: "144", name: "Madonna" },
  { id: "145", name: "Mae West" },
  { id: "146", name: "Björk" },
  { id: "147", name: "Alaska 5000" },
  { id: "148", name: "Ariana Grande" },
  { id: "149", name: "Paul Lynde" },
  { id: "150", name: "Jenifer Lewis" },
  { id: "151", name: "Crystal LaBeija" },
  { id: "152", name: "Grace Jones" },
  { id: "153", name: "Phaedra Parks" },
  { id: "154", name: "Caitlyn Jenner" },
  { id: "155", name: "Barbra Streisand" },
  { id: "156", name: "Della Reese" },
  { id: "157", name: "Walter Mercado" },
  { id: "158", name: "Flavor Flav" },
  { id: "159", name: "Ellen DeGeneres" },
  { id: "160", name: "Phyllis Diller" },
  { id: "161", name: "Divine" },
  { id: "162", name: "Dolly Parton" },
  { id: "163", name: "La Toya Jackson" },
  { id: "164", name: "Kim Cattrall" },
  { id: "165", name: "Natasha Lyonne" },
  { id: "166", name: "Judy Garland" },
  { id: "167", name: "Lucifer" },
  { id: "168", name: "Mike Tyson" },
  { id: "169", name: "Madame" },
  { id: "170", name: "Prince" },
  { id: "171", name: "The Lady Chablis" },
  { id: "172", name: "Joanna Lumley" },
  { id: "173", name: "Catherine Tate" },
  { id: "174", name: "The Bogeyman" },
  { id: "175", name: "Miss J" },
  { id: "176", name: "Joan Collins" },
  { id: "177", name: "Lily Tomlin" },
  { id: "178", name: "Abraham Lincoln" },
  { id: "179", name: "Elizabeth Taylor" },
  { id: "180", name: "The Sun" },
  { id: "181", name: "Frankie Grande" },
  { id: "182", name: "Reba McEntire" },
  { id: "183", name: "Jennifer Coolidge" },
  { id: "184", name: "Shirley Temple" },
  { id: "185", name: "Renee Graziano" },
  { id: "186", name: "Blackbeard" },
  { id: "187", name: "Marla Gibbs" },
  { id: "188", name: "Pal" },
  { id: "189", name: "Liberace" },
  { id: "190", name: "Ali Wong" },
  { id: "191", name: "John Leguizamo" },
  { id: "192", name: "Cleopatra" },
  { id: "193", name: "Pitbull" },
  { id: "194", name: "Jane Lynch" },
  { id: "195", name: "Zsa Zsa Gabor" },
  { id: "196", name: "Pete Burns" },
  { id: "197", name: "Natalie Nunn" },
  { id: "198", name: "Count Dracula" },
  { id: "199", name: "Chrissy Teigen" },
  { id: "200", name: "Kevin Hart" },
  { id: "201", name: "Erika Jayne" },
  { id: "202", name: "David Bowie" },
  { id: "203", name: "Margaret Thatcher" },
  { id: "204", name: "Donald Trump" },
  { id: "205", name: "Mary Berry" },
  { id: "206", name: "Gemma Collins" },
  { id: "207", name: "David Attenborough" },
  { id: "208", name: "Katie Price" },
  { id: "209", name: "Matt Lucas" },
  { id: "210", name: "Psychic Sally" },
  { id: "211", name: "Louie Spence" },
  { id: "212", name: "Miriam Margolyes" },
  { id: "213", name: "Macaulay Culkin" },
  { id: "214", name: "Elizabeth I" },
  { id: "215", name: "Saint Patrick" },
  { id: "216", name: "Cilla Black" },
  { id: "217", name: "Shirley Bassey" },
  { id: "218", name: "Lil Nas X" },
  { id: "219", name: "Kate Bush" },
  { id: "220", name: "Robin Williams" },
  { id: "221", name: "Elvis Presley" },
  { id: "222", name: "Nadine Coyle" },
  { id: "223", name: "Queen Victoria" },
  { id: "224", name: "Miss Coco Peru" },
  { id: "225", name: "Bonnie Tyler" },
  { id: "226", name: "JoJo Siwa" },
  { id: "227", name: "Mike Myers" },
  { id: "228", name: "Kathy Bates" },
  { id: "229", name: "Billy Porter" },
  { id: "230", name: "Manny Pacquiao" },
  { id: "231", name: "Statue Of Liberty" },
  { id: "232", name: "Kim Woodburn" },
  { id: "233", name: "Édith Piaf" },
  { id: "234", name: "Gypsy Rose Blanchard" },
  { id: "235", name: "Grimes" },
  { id: "236", name: "Jim Carrey" },
  { id: "237", name: "La Veneno" },
  { id: "238", name: "Kris Jenner" },
  { id: "239", name: "Marie Curie" },
  { id: "240", name: "Kourtney Kardashian" },
  { id: "241", name: "Joe Exotic" },
  { id: "242", name: "Jesus" },
  { id: "243", name: "Bettie Page" },
  { id: "244", name: "Jennifer Tilly" },
  { id: "245", name: "Mary-Kate Olsen" },
  { id: "246", name: "Keke Palmer" },
  { id: "247", name: "Albert Einstein" },
  { id: "248", name: "Marjorie Taylor Greene" },
  { id: "249", name: "Justin Trudeau" },
  { id: "250", name: "Big Freedia" },
  { id: "251", name: "Lizzo" },
  { id: "252", name: "Susan Boyle" },
  { id: "253", name: "Ron DeSantis" },
  { id: "254", name: "Elizabeth II" },
  { id: "255", name: "Dr. Seuss" },
  { id: "256", name: "Catherine O'Hara" },
  { id: "257", name: "Barry Humphries" },
  { id: "258", name: "Orville Peck" },
  { id: "259", name: "Val Garland" },
  { id: "260", name: "Jane Turner" },
  { id: "261", name: "Mrs. Claus" },
  { id: "262", name: "Lindsay Lohan" },
  { id: "263", name: "Mother Nature" },
  { id: "264", name: "María Clara" },
  { id: "265", name: "The Grim Reaper" },
  { id: "266", name: "Confucius" },
  { id: "267", name: "Verónica Castro" },
  { id: "268", name: "La Llorona" },
  { id: "269", name: "Inês Brasil" },
  { id: "270", name: "Bruce Darnell" },
  { id: "271", name: "Arnold Schwarzenegger" },
  { id: "272", name: "Wolfgang Amadeus Mozart" },
  { id: "273", name: "Ludwig Van Beethoven" },
  { id: "274", name: "Princess Diana" },
  { id: "275", name: "Valentino" },
  { id: "276", name: "King Kong" },
  { id: "277", name: "Laura León" },
  { id: "278", name: "Loreen" },
  { id: "279", name: "Susanne Bartsch" },
  { id: "280", name: "Annie Oakley" },
  { id: "281", name: "Zeus" }

];
