window.TALENT_SHOW_ACTS = [
  { id: "001", name: "Original Song" },
  { id: "002", name: "Comedy Performance" },
  { id: "003", name: "Comedy Skit" },
  { id: "004", name: "Lip Sync" },
  { id: "005", name: "Puppet Comedy Routine" },
  { id: "006", name: "Burlesque" },
  { id: "007", name: "Live Singing" },
  { id: "008", name: "Stand-Up" },
  { id: "009", name: "Original Comedy Song" },
  { id: "010", name: "Lipsync Performance" },
  { id: "011", name: "Spoken Word" },
  { id: "012", name: "Dancing" },
  { id: "013", name: "Voguing" },
  { id: "014", name: "Performance Art" },
  { id: "015", name: "Jump Rope/Lip Sync" },
  { id: "016", name: "Ballet Number" },
  { id: "017", name: "Electric Guitar" },
  { id: "018", name: "Cheerleading Comedy Routine" },
  { id: "019", name: "Original Song/Taekwondo" },
  { id: "020", name: "Ballet/Comedy Routine" },
  { id: "021", name: "Opera Singing" },
  { id: "022", name: "Water Sleeves/Cultural Dance" },
  { id: "023", name: "Live Singing/Impressions" },
  { id: "024", name: "Tap Dancing" },
  { id: "025", name: "Folk Dance" },
  { id: "026", name: "Rollerskating" },
  { id: "027", name: "Gymnastics" },
  { id: "028", name: "Violin" },
  { id: "029", name: "Baton" },
  { id: "030", name: "Kabuki" },
  { id: "031", name: "Color Guard" },
  { id: "032", name: "Painting" },
  { id: "033", name: "Celebrity Impersonations" },
  { id: "034", name: "Piano" },
  { id: "035", name: "Bubble Burlesque" },
  { id: "036", name: "Cheerleading" },
  { id: "037", name: "Juggling" },
  { id: "038", name: "Belly Dancing" },
  { id: "039", name: "Live Painting/Comedy" },
  { id: "040", name: "Original Song/Waacking" },
  { id: "041", name: "Quick Change" },
  { id: "042", name: "Original Song/Silk Veil Poi" },
  { id: "043", name: "Magic Show" },
  { id: "044", name: "Pole Dancing" },
  { id: "045", name: "Salsa Dancing" },
  { id: "046", name: "Rapping" },
  { id: "047", name: "Posing/Spoken Word" },
  { id: "048", name: "Contemporary Mouth Art" },
  { id: "049", name: "Ballooning" },
  { id: "050", name: "Quick Change Magic" },
  { id: "051", name: "Modern Dance" },
  { id: "052", name: "Lip Sync/Fan Dance" },
  { id: "053", name: "Slapstick Comedy" },
  { id: "054", name: "Live Singing With Ventriloquist Puppet" },
  { id: "055", name: "Lipsync Show" },
  { id: "056", name: "Ballroom Dancing And Lipsync" },
  { id: "057", name: "Comedy Painting" },
  { id: "058", name: "Mimic Imitation" },
  { id: "059", name: "Acrobatics" },
  { id: "060", name: "Comedy Sketch" },
  { id: "061", name: "Spoken Word/Live Singing" },
  { id: "062", name: "Live Singing/DJing" },
  { id: "063", name: "Fetish Routine" },
  { id: "064", name: "Ballet Dancing" },
  { id: "065", name: "Plate Spinning" },
  { id: "066", name: "Speed Sewing" },
  { id: "067", name: "Aerial Gymnastics" },
  { id: "068", name: "Monologue" },
  { id: "069", name: "Comedic Poetry" },
  { id: "070", name: "Saxophone" },
  { id: "071", name: "Dance" },
  { id: "072", name: "Puppet Show" },
  { id: "073", name: "Sexy Spoken Poetry" },
  { id: "074", name: "News Reporting Skit" },
  { id: "075", name: "Sword Balancing" },
  { id: "076", name: "Striptease" },
  { id: "077", name: "Fire Dancing" },
  { id: "078", name: "Dance Tutorial" },
  { id: "079", name: "Samba Performance" },
  { id: "080", name: "Lip Syncing/Whip Tricks" },
  { id: "081", name: "Trapeze" },
  { id: "082", name: "Glow Stick Dance" },
  { id: "083", name: "Movie Scene Recreation" },
  { id: "084", name: "Hula Hoop Routine" },
  { id: "085", name: "Martial Arts" },
  { id: "086", name: "Slam Poetry" },
  { id: "087", name: "Shadow Dance" },
  { id: "088", name: "Yo-Yo Tricks" },
  { id: "089", name: "Speed Cup Stacking" },
  { id: "090", name: "Trampoline" },
  { id: "091", name: "Mime" },
  { id: "092", name: "Science Experiment" },
  { id: "093", name: "Unicycling" },
  { id: "094", name: "Ribbon" },
  { id: "095", name: "Faux-Cumentary" },
  { id: "096", name: "Comical Fashion Show" },
  { id: "097", name: "Speed Origami" },
  { id: "098", name: "Flute" },
  { id: "099", name: "Harmonica" },
  { id: "100", name: "Harp" }
];
